// comic-theme/src/components/footer.vue
<!-- 页面脚部 -->

<template>
  <!-- mobile -->
  <div class="mobile-footer-wrapper" v-if="inMobile">
    <div
      class="second-text-btn mobile"
      v-for="(item, index) in freelogEntrances.filter((_, entrancesIndex) => entrancesIndex < 2)"
      :key="item.label"
      @click="toPage(item.url)"
    >
      <i :class="item.label" v-if="index === 0"></i>
      <span v-else>{{ item.label }}</span>
    </div>
  </div>

  <!-- PC -->
  <div class="footer-wrapper" v-if="!inMobile">
    <div class="second-text-btn" v-for="(item, index) in freelogEntrances" :key="item.label" @click="toPage(item.url)">
      <i :class="item.label" v-if="index === 0"></i>
      <span v-else>{{ item.label }}</span>
    </div>
  </div>
</template>

<script lang="ts">
import { useStore } from "vuex";
import { freelogEntrances } from "@/api/data";
import { toRefs } from "vue";

export default {
  name: "my-footer",

  setup() {
    const store = useStore();

    const methods = {
      /** 跳转页面 */
      toPage(url: string) {
        window.open(url);
      },
    };

    return {
      freelogEntrances,
      ...toRefs(store.state),
      ...methods,
    };
  },
};
</script>

<style lang="scss" scoped>
// mobile
.mobile-footer-wrapper {
  position: absolute;
  left: 0;
  bottom: 0;
  right: 0;
  height: 98px;
  background-color: rgba(0, 0, 0, 0.03);
  display: flex;
  align-items: center;
  justify-content: center;

  .second-text-btn {
    font-size: 14px;
    line-height: 18px;
  }
}

// PC
.footer-wrapper {
  position: absolute;
  left: 0;
  bottom: 0;
  right: 0;
  height: 48px;
  background-color: #fafbfc;
  display: flex;
  align-items: center;
  justify-content: center;

  .second-text-btn {
    font-size: 12px;
  }
}

.second-text-btn {
  padding: 0 20px;

  & + .second-text-btn {
    border-left: 1px solid rgba(0, 0, 0, 0.15);
  }
}
</style>

// novel-theme/src/components/footer/footer.tsx
import { useContext } from "react";
import { freelogEntrances } from "../../api/data";
import { globalContext } from "../../router";
import "./footer.scss";

/** 页面脚部 */
export const Footer = () => {
  const { inMobile } = useContext(globalContext);

  if (inMobile === true) {
    // mobile
    return (
      <div className="mobile-footer-wrapper">
        {freelogEntrances
          .filter((_, entrancesIndex) => entrancesIndex < 2)
          .map((item, index) => (
            <div className="second-text-btn mobile" key={item.label} onClick={() => window.open(item.url)}>
              {index === 0 ? <i className={item.label}></i> : <span>{item.label}</span>}
            </div>
          ))}
      </div>
    );
  } else if (inMobile === false) {
    // PC
    return (
      <div className="footer-wrapper">
        {freelogEntrances.map((item, index) => (
          <div className="second-text-btn" key={item.label} onClick={() => window.open(item.url)}>
            {index === 0 ? <i className={item.label}></i> : <span>{item.label}</span>}
          </div>
        ))}
      </div>
    );
  } else {
    return <></>;
  }
};
