// novel-theme/src/screens/home/home.tsx
import "./home.scss";
import MyFilter from "../../assets/images/filter.png";
import { useState, useEffect, useCallback, useRef, useContext } from "react";
import { Header } from "../../components/header/header";
import { getExhibitAuthStatus, getExhibitListByPaging, GetExhibitListByPagingParams } from "../../api/freelog";
import { ExhibitItem } from "../../api/interface";
import { Novel } from "../../components/novel/novel";
import { useMyHistory, useMyScroll, useMyShelf } from "../../utils/hooks";
import { globalContext } from "../../router";
import { ThemeEntrance } from "../../components/theme-entrance/theme-entrance";
import { Footer } from "../../components/footer/footer";
import { LoginBtn } from "../../components/login-btn/login-btn";
import CSSTransition from "react-transition-group/CSSTransition";
import { Loader } from "../../components/loader/loader";

export const HomeScreen = (props: any) => {
  const { tags, keywords } = props.match.params;
  const { inMobile } = useContext(globalContext);
  const { scrollTop, clientHeight, scrollHeight } = useMyScroll();
  const [bookList, setBookList] = useState<ExhibitItem[]>([]);
  const [total, setTotal] = useState<number | null>(null);
  const [searching, setSearching] = useState(false);
  const [loading, setLoading] = useState(false);
  let skip = useRef(0);

  const getBookList = useCallback(
    async (init = false) => {
      if (loading) return;

      setSearching(!!keywords);

      if (total === bookList.length && !init) return;

      setLoading(true);
      skip.current = init ? 0 : skip.current + 30;
      const queryParams: GetExhibitListByPagingParams = {
        omitArticleResourceType: "theme",
        skip: skip.current,
        limit: 30,
      };
      if (tags !== "全部") queryParams.tags = tags;
      if (keywords) queryParams.keywords = keywords;

      const list = await getExhibitListByPaging(queryParams);
      const { dataList, totalItem } = list.data.data;
      if (dataList.length !== 0) {
        const idList: string[] = [];
        dataList.forEach((item: ExhibitItem) => {
          idList.push(item.exhibitId);
        });
        const ids = idList.join(",");
        const statusInfo = await getExhibitAuthStatus(ids);
        if (statusInfo.data.data) {
          statusInfo.data.data.forEach((item: { exhibitId: string; isAuth: boolean }) => {
            const index = dataList.findIndex((listItem: ExhibitItem) => listItem.exhibitId === item.exhibitId);
            dataList[index].isAuth = item.isAuth;
          });
        }
      }
      setBookList((pre) => (init ? dataList : [...pre, ...dataList]));
      setTotal(totalItem);
      setLoading(false);
    },
    // eslint-disable-next-line
    [bookList.length, total, tags, keywords]
  );

  useEffect(() => {
    if (scrollTop + clientHeight === scrollHeight && scrollTop) getBookList();
  }, [scrollTop, clientHeight, scrollHeight, getBookList]);

  useEffect(() => {
    getBookList(true);
    // eslint-disable-next-line
  }, [tags, keywords]);

  return (
    <div className="home-wrapper">
      <Header homeHeader={!searching} mobileSearching={(inMobile && searching) || false} defaultSearchKey={keywords} />

      <HomeBody
        bookList={bookList}
        searching={searching}
        total={total}
        tags={tags}
        keywords={keywords}
        loading={loading}
      />

      <Footer />

      <LoginBtn />

      <ThemeEntrance />
    </div>
  );
};

const HomeBody = (props: {
  bookList: ExhibitItem[];
  searching: boolean;
  total: number | null;
  tags: string;
  keywords: string;
  loading: boolean;
}) => {
  const { bookList, searching, total, tags, keywords, loading } = props;
  const { inMobile, userData, selfConfig } = useContext(globalContext);
  const tagsList: string[] = selfConfig.tags?.split(",");
  const { myShelf } = useMyShelf();
  const history = useMyHistory();
  const [filterBoxShow, setFilterBoxShow] = useState(false);

  const selectTag = (tag: string) => {
    let url = `/home/${tag}`;
    if (keywords) url += `/${keywords}`;
    history.switchPage(url);
  };

  if (loading) {
    return <Loader />;
  } else if (inMobile === true) {
    // mobile
    return (
      <div className="mobile-home-body">
        {!searching && userData?.isLogin && myShelf && myShelf.length !== 0 && (
          <div className="shelf-book-list">
            <div className="shelf-header">
              <div className="box-title">我的书架</div>
              <div className="more-shelf" onClick={() => history.switchPage("/shelf")}>
                全部{myShelf.length}
                <i className="freelog fl-icon-zhankaigengduo"></i>
              </div>
            </div>

            <div className="book-list-box">
              {myShelf.map((item) => {
                return (
                  <div className="book-box" key={item.exhibitId}>
                    <Novel mode={4} data={item}></Novel>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        <div className="book-list">
          {searching ? (
            <div className="search-box-title">
              <div className="box-title">查询到{bookList.length}个相关结果</div>
              <div className="filter-btn" onClick={() => setFilterBoxShow(true)}>
                <img className="filter-img" src={MyFilter} alt="" />
                <div className="filter-label">筛选</div>
              </div>
            </div>
          ) : (
            <div className="box-header">
              <div className="box-title">精选小说</div>
              <div className="filter-btn" onClick={() => setFilterBoxShow(true)}>
                <img className="filter-img" src={MyFilter} alt="" />
                <div className="filter-label">筛选</div>
              </div>
            </div>
          )}

          {bookList.map((item) => {
            return (
              <div key={item.exhibitId} className="book-box">
                <Novel data={item}></Novel>
              </div>
            );
          })}

          {bookList.length === 0 && <div className="tip">当前节点暂无任何书籍，请稍后查看</div>}

          {bookList.length !== 0 && bookList.length === total && <div className="tip no-more">— 已加载全部书籍 —</div>}
        </div>

        <CSSTransition in={filterBoxShow} classNames="fade" timeout={200} unmountOnExit>
          <div id="modal" className="modal" onClick={() => setFilterBoxShow(false)}></div>
        </CSSTransition>
        <CSSTransition in={filterBoxShow} classNames="slide-right" timeout={200} unmountOnExit>
          <div className="filter-box-body">
            <div className="filter-box-header">
              <div className="header-title">按标签筛选</div>
              <div className="close-btn" onClick={() => setFilterBoxShow(false)}>
                <i className="freelog fl-icon-guanbi"></i>
              </div>
            </div>
            <div className="tags-box">
              <div
                className={`tag ${tags === "全部" && "active"}`}
                onClick={() => {
                  setFilterBoxShow(false);
                  selectTag("全部");
                }}
              >
                全部
              </div>
              <div className="tags-box-list">
                {tagsList.map((item) => (
                  <div
                    className={`tag ${tags === item && "active"}`}
                    key={item}
                    onClick={() => {
                      setFilterBoxShow(false);
                      selectTag(item);
                    }}
                  >
                    {item}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </CSSTransition>
      </div>
    );
  } else if (inMobile === false) {
    // PC
    return (
      <div className="home-body">
        {!searching && userData?.isLogin && myShelf && myShelf.length !== 0 && (
          <div className="book-list">
            <div className="shelf-header">
              <div className="box-title">我的书架</div>
              <div className="shelf-header-right">
                <div className="shelf-length">全部{myShelf.length}</div>
                <div className="text-btn" onClick={() => history.switchPage("/shelf")}>
                  管理书架
                </div>
              </div>
            </div>

            <div className="book-list-box">
              {myShelf.map((item) => {
                return (
                  <div className="book-box" key={item.exhibitId}>
                    <Novel data={item}></Novel>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        <div className="book-list">
          {searching ? (
            <div className="search-box-title">查询到{bookList.length}个相关结果</div>
          ) : (
            <div className="box-title">精选小说</div>
          )}

          <div className="filter-bar">
            <div className="filter-bar-bg"></div>

            <div className={`category-btn ${tags === "全部" && "active"}`} onClick={() => selectTag("全部")}>
              全部
            </div>

            {tagsList.map((item) => {
              return (
                <div className={`category-btn ${tags === item && "active"}`} key={item} onClick={() => selectTag(item)}>
                  {item}
                </div>
              );
            })}
          </div>

          <div className="book-list-box">
            {bookList.map((item) => {
              return (
                <div key={item.exhibitId} className="book-box">
                  <Novel data={item}></Novel>
                </div>
              );
            })}
          </div>

          {bookList.length === 0 && <div className="tip">当前节点暂无任何书籍，请稍后查看</div>}

          {bookList.length !== 0 && bookList.length === total && <div className="tip no-more">— 已加载全部书籍 —</div>}
        </div>
      </div>
    );
  } else {
    return <div></div>;
  }
};

// gallery-theme/src/views/home.vue
<template>
  <div class="home-wrapper">
    <my-header :homeHeader="!searchData.keywords" :mobileSearching="!!(inMobile && searchData.keywords)" />

    <!-- mobile -->
    <div class="mobile-home-body" v-if="inMobile">
      <div class="header" v-if="searchData.keywords">
        <div class="box-title">查询到{{ listData.length }}个相关结果</div>

        <div class="filter-btn" @click="filterBoxShow = true">
          <img class="filter-img" src="../assets/images/filter.png" />
          <div class="filter-label">筛选</div>
        </div>
      </div>

      <div class="frame-list">
        <div class="waterfall" v-for="list in listNumber" :key="list">
          <my-frame
            class="frame"
            :data="item"
            v-for="item in waterfall[waterfallList[list - 1]]"
            :key="item.exhibitId"
            @click="clickFrame(item.exhibitId)"
          />
        </div>
      </div>

      <div className="tip" v-show="!loading && total === 0">当前节点暂无数据，请稍后查看</div>
      <div className="tip no-more" v-show="!loading && listData.length !== 0 && listData.length === total">
        — 已加载全部 —
      </div>

      <transition name="fade">
        <div id="modal" class="modal" v-if="filterBoxShow" @click="filterBoxShow = false"></div>
      </transition>
      <transition name="slide-right">
        <div class="filter-box-body" v-if="filterBoxShow">
          <div class="filter-box-header">
            <div class="header-title">按标签筛选</div>
            <div class="close-btn" @click="filterBoxShow = false">
              <i class="freelog fl-icon-guanbi"></i>
            </div>
          </div>
          <div class="tags-box">
            <div
              class="tag"
              :class="{ active: !searchData.tags }"
              @click="
                filterBoxShow = false;
                selectTag();
              "
            >
              全部
            </div>
            <div class="tags-box-list">
              <div
                class="tag"
                :class="{ active: searchData.tags === item }"
                v-for="item in tagsList"
                :key="item"
                @click="
                  filterBoxShow = false;
                  selectTag(item);
                "
              >
                {{ item }}
              </div>
            </div>
          </div>
        </div>
      </transition>
    </div>

    <!-- PC -->
    <div class="home-body" v-if="!inMobile">
      <div class="search-box-title" v-if="searchData.keywords">查询到{{ listData.length }}个相关结果</div>

      <div class="filter-bar">
        <div class="filter-bar-bg"></div>

        <div class="category-btn" :class="{ active: !searchData.tags }" @click="selectTag()">全部</div>

        <div
          class="category-btn"
          :class="{ active: searchData.tags === item }"
          v-for="item in tagsList"
          :key="item"
          @click="selectTag(item)"
        >
          {{ item }}
        </div>
      </div>

      <div class="frame-list">
        <div class="waterfall" v-for="list in listNumber" :key="list">
          <my-frame
            class="frame"
            :data="item"
            v-for="item in waterfall[waterfallList[list - 1]]"
            :key="item.exhibitId"
            @click="clickFrame(item.exhibitId)"
          />
        </div>
      </div>

      <div className="tip" v-show="!loading && total === 0">当前节点暂无数据，请稍后查看</div>
      <div className="tip no-more" v-show="!loading && listData.length !== 0 && listData.length === total">
        — 已加载全部 —
      </div>
    </div>

    <my-footer />

    <login-btn />

    <detail v-model:id="currentId" v-if="!inMobile" />
  </div>
</template>

<script lang="ts">
import { defineAsyncComponent, onUnmounted, reactive, toRefs, watch } from "vue";
import { useGetList, useMyRouter, useMyScroll, useMyWaterfall } from "../utils/hooks";
import { useStore } from "vuex";
import { ExhibitItem } from "@/api/interface";

export default {
  name: "home",

  components: {
    "my-header": defineAsyncComponent(() => import("../components/header.vue")),
    "my-footer": defineAsyncComponent(() => import("../components/footer.vue")),
    "my-frame": defineAsyncComponent(() => import("../components/frame.vue")),
    detail: defineAsyncComponent(() => import("../views/detail.vue")),
    "login-btn": defineAsyncComponent(() => import("../components/login-btn.vue")),
  },

  setup() {
    const store = useStore();
    const tagsList: string[] = store.state.selfConfig.tags?.split(",");
    const { query, switchPage } = useMyRouter();
    const { listNumber, waterfall, waterfallList, getListNumber, initWaterfall, setWaterFall } = useMyWaterfall();
    const { scrollTop, clientHeight, scrollHeight } = useMyScroll();
    const datasOfGetList = useGetList();

    const data = reactive({
      searchData: {} as {
        keywords?: string;
        tags?: string;
        id?: string;
      },
      currentId: null as null | string,
      filterBoxShow: false,
    });

    const methods = {
      // 清除搜索
      clearSearch() {
        data.searchData = {};
        switchPage("/home");
      },

      // 筛选标签
      selectTag(tag: string) {
        const { keywords } = data.searchData;
        const query: { keywords?: string; tags?: string } = {};
        if (tag) query.tags = tag;
        if (keywords) query.keywords = keywords;
        switchPage("/home", query);
      },

      clickFrame(id: string) {
        if (store.state.inMobile) {
          switchPage("/detail", { id });
        } else {
          data.currentId = id;
        }
        store.commit("setData", { key: "listData", value: datasOfGetList.listData.value });
      },
    };

    // 获取数据
    const getData = () => {
      data.searchData = query.value;
      datasOfGetList.clearData();
      datasOfGetList.getList(data.searchData, true);
    };

    // 获取更多数据
    const getMoreData = () => {
      if (scrollTop.value + clientHeight.value === scrollHeight.value) {
        datasOfGetList.getList();
      }
    };

    // 屏幕尺寸变化切换瀑布流列数
    const waterfallResize = () => {
      getListNumber();
      initWaterfall();
      setWaterFall(datasOfGetList.listData.value);
    };

    // 根据链接判断是否进入详情页或打开内容弹窗
    const judgeUrl = () => {
      const { id } = query.value;
      if (!id) return;

      if (store.state.inMobile) {
        // 移动端跳转详情页面
        switchPage("/home", {}, "replace");
        setTimeout(() => {
          switchPage("/detail", { id });
        }, 0);
      } else {
        // PC端弹出内容弹窗
        data.currentId = id;
      }
    };

    watch(
      () => query.value,
      (cur, pre) => {
        if (cur.keywords !== pre.keywords || cur.tags !== pre.tags) getData();
      }
    );

    watch(
      () => scrollTop.value,
      () => {
        getMoreData();
      }
    );

    watch(
      () => datasOfGetList.listData.value,
      async (cur: ExhibitItem[], pre: ExhibitItem[]) => {
        if (datasOfGetList.skip.value === 0) initWaterfall();

        const index = datasOfGetList.skip.value;
        const { inMobile } = store.state;
        let num = 0;
        let frameWidth = 0;
        let minHeight = 0;

        if (inMobile) {
          frameWidth = (document.body.clientWidth - 40) / 2;
          minHeight = 120;
        } else {
          frameWidth = 300;
          minHeight = 230;
        }

        for (let i = index; i < cur.length; i++) {
          const img = new Image();
          img.src = cur[i].coverImages[0];
          img.onload = () => {
            const height = (frameWidth / img.width) * img.height;
            cur[i].height = height < minHeight ? minHeight : height;
            num++;

            if (num === cur.length - pre.length) setWaterFall(cur, index);
          };
        }
      }
    );

    window.addEventListener("resize", waterfallResize);
    onUnmounted(() => {
      window.removeEventListener("resize", waterfallResize);
    });

    judgeUrl();
    getListNumber();
    getData();

    return {
      ...toRefs(store.state),
      tagsList,
      switchPage,
      listNumber,
      waterfall,
      waterfallList,
      ...datasOfGetList,
      ...toRefs(data),
      ...methods,
    };
  },
};
</script>

<style lang="scss" scoped>
.home-wrapper {
  position: relative;
  width: 100%;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;

  // mobile
  .mobile-home-body {
    width: 100%;
    padding: 15px 15px 0;
    box-sizing: border-box;
    padding-bottom: 98px;

    .header {
      margin: 15px 0 30px;
      display: flex;
      align-items: center;
      justify-content: space-between;

      .box-title {
        font-size: 16px;
        color: #999999;
        line-height: 22px;
      }

      .filter-btn {
        display: flex;
        align-items: center;

        .filter-img {
          width: 18px;
          height: 18px;
        }

        .filter-label {
          font-size: 16px;
          color: #c127ff;
          line-height: 22px;
          margin-left: 5px;
        }
      }
    }

    .frame-list {
      display: flex;

      .waterfall {
        flex: 1;
        width: 0;

        & + .waterfall {
          margin-left: 10px;
        }

        .frame-wrapper + .frame-wrapper {
          margin-top: 10px;
        }
      }
    }

    .tip {
      width: 100%;
      text-align: center;
      font-size: 16px;
      line-height: 22px;
      color: #999;
      margin-top: 55px;

      &.no-more {
        font-size: 14px;
        line-height: 20px;
        margin: 30px 0;
      }
    }

    .modal {
      position: fixed;
      left: 0;
      top: 0;
      right: 0;
      bottom: 0;
      background-color: rgba(0, 0, 0, 0.4);
      z-index: 101;
    }

    .filter-box-body {
      position: fixed;
      left: 0;
      top: 0;
      bottom: 0;
      width: 340px;
      background: #ffffff;
      border-radius: 0px 10px 10px 0px;
      padding: 0 20px;
      box-sizing: border-box;
      overflow: hidden;
      display: flex;
      flex-direction: column;
      z-index: 101;

      .filter-box-header {
        position: relative;
        width: 100%;
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-top: 26px;

        .header-title {
          font-size: 16px;
          font-weight: 600;
          color: #222222;
          line-height: 22px;
        }

        .close-btn {
          width: 22px;
          height: 22px;
          display: flex;
          align-items: center;
          justify-content: center;
          margin-right: 6px;

          .freelog {
            font-size: 12px;
            color: #333;
            display: flex;
            align-items: center;
            justify-content: center;
          }
        }
      }

      .tags-box {
        width: 100%;
        flex: 1;
        display: flex;
        flex-direction: column;
        margin-top: 30px;
        padding-left: 12px;
        box-sizing: border-box;

        .tags-box-list {
          width: 100%;
          display: flex;
          flex-wrap: wrap;
          margin-top: 15px;
        }

        .tag {
          width: fit-content;
          height: 38px;
          border-radius: 38px;
          padding: 9px 15px;
          box-sizing: border-box;
          background: #ebecf0;
          font-size: 14px;
          color: #575e6a;
          line-height: 20px;
          margin: 0 5px 15px;
          cursor: pointer;

          &.active {
            background: #6ea29e;
            color: #fff;
          }
        }
      }
    }
  }

  // PC
  .home-body {
    width: 1230px;
    padding-top: 10px;
    padding-bottom: 148px;

    .search-box-title {
      font-size: 14px;
      color: #999999;
      line-height: 20px;
      margin-top: 20px;
    }

    .filter-bar {
      position: relative;
      width: 100%;
      height: 64px;
      border-radius: 6px;
      display: flex;
      align-items: center;
      justify-content: center;
      overflow: hidden;
      margin-top: 30px;
      margin-bottom: 40px;

      .filter-bar-bg {
        position: absolute;
        inset: 0;
        background-color: var(--deriveColor);
        opacity: 0.08;
      }

      .category-btn {
        position: relative;
        height: 24px;
        padding: 2px 8px;
        box-sizing: border-box;
        font-size: 14px;
        color: #666;
        line-height: 20px;
        border-radius: 12px;
        cursor: pointer;
        transition: all 0.2s linear;
        z-index: 1;

        &:hover {
          color: var(--deriveColor);
        }

        &:active {
          color: var(--deriveColor);
          opacity: 0.8;
        }

        &.active {
          background-color: var(--deriveColor);
          color: #fff;
        }

        & + .category-btn {
          margin-left: 4px;
        }
      }
    }

    .frame-list {
      display: flex;

      .waterfall {
        width: 300px;

        & + .waterfall {
          margin-left: 10px;
        }

        .frame-wrapper + .frame-wrapper {
          margin-top: 10px;
        }
      }
    }

    .tip {
      width: 100%;
      text-align: center;
      font-size: 16px;
      line-height: 22px;
      color: #999;
      margin-top: 55px;

      &.no-more {
        font-size: 14px;
        line-height: 20px;
        margin-top: 30px;
      }
    }
  }
}

@media (min-width: 1600px) {
  .home-body {
    width: 1540px !important;
  }
}
</style>
