// novel-theme/src/components/back-top/back-top.tsx
import "./back-top.scss";
import CSSTransition from "react-transition-group/CSSTransition";
import { useMyScroll } from "../../utils/hooks";
import { ReactChild } from "react";

export const BackTop = (props: { children: ReactChild; onClick?: () => void }) => {
  const { scrollTop } = useMyScroll();
  const { children, onClick } = props;

  const backToTop = () => {
    onClick && onClick();
    document.documentElement.scroll({ top: 0, behavior: "smooth" });
    document.body.scroll({ top: 0, behavior: "smooth" });
  };

  return (
    <CSSTransition in={scrollTop > 300} classNames="fade" timeout={500} unmountOnExit onClick={() => backToTop()}>
      {children}
    </CSSTransition>
  );
};

// gallery-theme/src/components/back-top.vue
<template>
  <transition name="fade">
    <div @click.stop="backToTop()" v-show="topBtnShow"><slot></slot></div>
  </transition>
</template>

<script lang="ts">
import { ref, watch } from "vue";
import { useMyScroll } from "@/utils/hooks";

export default {
  name: "back-top",

  setup() {
    const { scrollTop } = useMyScroll();
    const topBtnShow = ref(false);

    const backToTop = () => {
      document.documentElement.scroll({ top: 0, behavior: "smooth" });
      document.body.scroll({ top: 0, behavior: "smooth" });
    };

    watch(
      () => scrollTop.value,
      (cur) => {
        topBtnShow.value = cur > 300;
      }
    );

    return {
      topBtnShow,
      backToTop,
    };
  },
};
</script>
