// theme/【1】novel-theme/src/screens/reader/reader.tsx
import React, { useContext, useRef } from "react";
import "./reader.scss";
import Lock from "../../assets/images/lock.png";
import BgImage from "../../assets/images/reader-bg.png";
import AuthLinkAbnormal from "../../assets/images/auth-link-abnormal.png";
import { useState, useEffect, useCallback } from "react";
import { ExhibitItem, ThemeItem } from "../../api/interface";
import {
  addAuth,
  getExhibitAuthStatus,
  getExhibitFileStream,
  getExhibitInfo,
  getSubDep,
  mountWidget,
} from "../../api/freelog";
import { readerThemeList } from "../../api/data";
import { BackTop } from "../../components/back-top/back-top";
import { useMyHistory, useMyScroll, useMyShelf } from "../../utils/hooks";
import { Header } from "../../components/header/header";
import { globalContext } from "../../router";
import { showToast } from "../../components/toast/toast";
import CSSTransition from "react-transition-group/CSSTransition";
import { Loader } from "../../components/loader/loader";
import { getUrlParams } from "../../utils/common";

export const readerContext = React.createContext<any>({});

/** 阅读页 */
export const ReaderScreen = (props: any) => {
  const { id } = getUrlParams(props.location.search);
  const { inMobile } = useContext(globalContext);
  const myTheme = JSON.parse(localStorage.getItem("theme") || "null");
  const [book, setBook] = useState<ExhibitItem | null>(null);
  const [fontSize, setFontSize] = useState(22);
  const [theme, setTheme] = useState<ThemeItem>(myTheme || readerThemeList[0]);
  const [fontSizePopupShow, setFontSizePopupShow] = useState(false);
  const [themePopupShow, setThemePopupShow] = useState(false);
  const [mobileBarShow, setMobileBarShow] = useState(true);
  const [loading, setLoading] = useState(true);
  const widgetList = useRef<any>({});

  /** 获取小说信息 */
  const getNovelInfo = useCallback(async () => {
    setLoading(true);
    const exhibitInfo = await getExhibitInfo(id, { isLoadVersionProperty: 1 });
    setBook(exhibitInfo.data.data);
  }, [id]);

  /** 加载分享插件 */
  const mountShareWidget = async () => {
    if (inMobile) return;

    if (widgetList.current.share) await widgetList.current.share.unmount();
    const themeData = await getSubDep();
    const widget = themeData.subDep.find(
      (item: any) => item.name === "ZhuC/Freelog插件-展品分享"
    );
    if (!widget) return;
    widgetList.current.share = await mountWidget({
      widget,
      container: document.getElementById("share"),
      topExhibitData: themeData,
      config: { exhibit: book, type: "小说" },
    });
  };

  /** 加载 markdown 插件 */
  const mountMarkdownWidget = async (
    exhibitInfo: ExhibitItem,
    content: string
  ) => {
    const themeData = await getSubDep();
    const widget = themeData.subDep.find(
      (item: any) => item.name === "ZhuC/Freelog插件-markdown解析"
    );
    if (!widget) return;
    const myFontSize = Number(localStorage.getItem("fontSize")) || 22;
    setFontSize(myFontSize);
    widgetList.current.markdown = await mountWidget({
      widget,
      container: document.getElementById("markdown"),
      topExhibitData: themeData,
      config: { exhibitInfo, content, fontSize: myFontSize },
      widget_entry: "https://localhost:8202",
    });
  };

  /** 通知插件更新数据 */
  const setWidgetData = (widget: string, key: string, value: any) => {
    if (
      widgetList.current[widget] &&
      widgetList.current[widget].getApi().setData
    ) {
      widgetList.current[widget].getApi().setData(key, value);
    }
  };

  /** 点击页面（关闭所有打开的弹窗） */
  const clickPage = () => {
    setWidgetData("share", "show", false);
    if (fontSizePopupShow) setFontSizePopupShow(false);
    if (themePopupShow) setThemePopupShow(false);
    if (inMobile) setMobileBarShow(true);
  };

  useEffect(() => {
    return () => {
      (async function unmountWidget() {
        // eslint-disable-next-line
        for (const key in widgetList.current) {
          // eslint-disable-next-line
          await widgetList.current[key].unmount();
        }
      })();
    };
  }, []);

  useEffect(() => {
    getNovelInfo();
    // eslint-disable-next-line
  }, [id]);

  useEffect(() => {
    setWidgetData("markdown", "fontSize", fontSize);
  }, [fontSize]);

  const context = {
    id,
    inMobile,
    book,
    setBook,
    fontSize,
    setFontSize,
    theme,
    setTheme,
    fontSizePopupShow,
    setFontSizePopupShow,
    themePopupShow,
    setThemePopupShow,
    mobileBarShow,
    setMobileBarShow,
    loading,
    setLoading,
    mountShareWidget,
    mountMarkdownWidget,
    setWidgetData,
  };

  return (
    <readerContext.Provider value={context}>
      <div
        className={`reader-wrapper ${inMobile && "in-mobile"}`}
        style={{
          backgroundImage: `url(${BgImage})`,
          backgroundColor: theme?.bgColor,
        }}
        onClick={() => clickPage()}
      >
        <CSSTransition
          in={(inMobile && mobileBarShow) || !inMobile}
          classNames="slide-up"
          timeout={150}
          unmountOnExit
        >
          <Header readerHeader={true} />
        </CSSTransition>
        <ReaderBody />
        <OperaterBtns />
      </div>
    </readerContext.Provider>
  );
};

/** 阅读页主体内容 */
const ReaderBody = () => {
  const history = useMyHistory();
  const { userData } = useContext(globalContext);
  const {
    inMobile,
    book,
    id,
    theme,
    mountMarkdownWidget,
    loading,
    setLoading,
  } = useContext(readerContext);
  const [content, setContent] = useState<string>("");
  const [defaulterIdentityType, setDefaulterIdentityType] = useState<
    number | null
  >(null);

  /** 获取小说内容 */
  const getContent = useCallback(async () => {
    let authErrType;
    const statusInfo = await getExhibitAuthStatus(id);
    if (statusInfo.data.data)
      authErrType = statusInfo.data.data[0].defaulterIdentityType;
    setDefaulterIdentityType(authErrType);

    if (authErrType === 0) {
      // 已签约并且授权链无异常
      const info: any = await getExhibitFileStream(id);
      if (!info) {
        setLoading(false);
        return;
      }
      setContent(info.data);
    } else if (authErrType === 4) {
      // 标的物未签约，自动弹出授权弹窗
      getAuth();
    }

    setLoading(false);
    // eslint-disable-next-line
  }, [id]);

  /** 获取授权 */
  const getAuth = async () => {
    const authResult = await addAuth(id);
    const { status } = authResult;
    if (status === 0) getContent();
  };

  useEffect(() => {
    getContent();
    // eslint-disable-next-line
  }, [id]);

  useEffect(() => {
    if (book && content) {
      setLoading(false);
      mountMarkdownWidget(book, content);
    }
    // eslint-disable-next-line
  }, [book, content]);

  if (loading) {
    return <Loader />;
  } else if (inMobile === true) {
    // mobile
    return (
      <div
        className={`mobile-body-wrapper ${
          theme?.type === 1 ? "dark" : "light"
        }`}
        style={
          {
            backgroundImage: `url(${BgImage})`,
            backgroundColor: theme?.bookColor,
          } as any
        }
      >
        {defaulterIdentityType === 0 && <div id="markdown" />}
        {![null, 0, 4].includes(defaulterIdentityType) ? (
          <div className="auth-box">
            <img
              className="auth-link-abnormal"
              src={AuthLinkAbnormal}
              alt="授权链异常"
            />
            <div className="auth-link-tip">授权链异常，无法查看</div>
            <div
              className="home-btn"
              onClick={() => history.switchPage("/home")}
            >
              进入首页
            </div>
          </div>
        ) : defaulterIdentityType &&
          (defaulterIdentityType === 4 || userData?.isLogin === false) ? (
          <div className="lock-box">
            <img className="lock" src={Lock} alt="未授权" />
            <div className="lock-tip">
              展品未开放授权，继续浏览请签约并获取授权
            </div>
            <div className="get-btn" onClick={() => getAuth()}>
              获得授权
            </div>
          </div>
        ) : null}
      </div>
    );
  } else if (inMobile === false) {
    // PC
    return (
      <div className="body-wrapper">
        <div className="breadcrumbs-wrapper">
          <div className="breadcrumbs-item">
            <div
              className="second-text-btn"
              onClick={() => history.switchPage(`/detail?id=${id}`)}
            >
              {book?.exhibitTitle}
            </div>
          </div>
        </div>

        <div
          className={`content ${theme?.type === 1 ? "dark" : "light"}`}
          style={
            {
              backgroundImage: `url(${BgImage})`,
              backgroundColor: theme?.bookColor,
            } as any
          }
        >
          {defaulterIdentityType === 0 && <div id="markdown" />}
          {![null, 0, 4].includes(defaulterIdentityType) ? (
            <div className="auth-box">
              <img
                className="auth-link-abnormal"
                src={AuthLinkAbnormal}
                alt="授权链异常"
              />
              <div className="auth-link-tip">授权链异常，无法查看</div>
              <div
                className="home-btn"
                onClick={() => history.switchPage("/home")}
              >
                进入首页
              </div>
            </div>
          ) : defaulterIdentityType &&
            (defaulterIdentityType === 4 || userData?.isLogin === false) ? (
            <div className="lock-box">
              <img className="lock" src={Lock} alt="未授权" />
              <div className="lock-tip">
                展品未开放授权，继续浏览请签约并获取授权
              </div>
              <div className="get-btn" onClick={() => getAuth()}>
                获得授权
              </div>
            </div>
          ) : null}
        </div>
      </div>
    );
  } else {
    return <></>;
  }
};

/** 功能操作按钮群 */
const OperaterBtns = () => {
  const { scrollTop } = useMyScroll();
  const {
    inMobile,
    book,
    fontSize,
    setFontSize,
    theme,
    setTheme,
    fontSizePopupShow,
    setFontSizePopupShow,
    themePopupShow,
    setThemePopupShow,
    mobileBarShow,
    setMobileBarShow,
    mountShareWidget,
    setWidgetData,
  } = useContext(readerContext);
  const { isCollected, operateShelf } = useMyShelf(book?.exhibitId);
  const [href, setHref] = useState("");
  let changingFontSize = useRef(false);
  let changingFontSizeTimer = useRef<any>(null);

  /** 改变字体大小 */
  const changeFontSize = (type: number) => {
    changingFontSize.current = true;
    clearTimeout(changingFontSizeTimer.current);
    changingFontSizeTimer.current = null;
    let result = fontSize;
    if (type === 0) {
      if (result === 14) return;
      result--;
    } else {
      if (result === 36) return;
      result++;
    }
    setFontSize(result);
    localStorage.setItem("fontSize", result);
    changingFontSizeTimer.current = setTimeout(() => {
      changingFontSize.current = false;
      clearTimeout(changingFontSizeTimer.current);
      changingFontSizeTimer.current = null;
    }, 500);
  };

  /** 关闭所有弹窗 */
  const closeAllPopup = () => {
    setWidgetData("share", "show", false);
    setFontSizePopupShow(false);
    setThemePopupShow(false);
  };

  /** 移动端分享 */
  const share = () => {
    // 复制链接
    const input: any = document.getElementById("href");
    input.select();
    document.execCommand("Copy");
    showToast("链接复制成功～");
  };

  useEffect(() => {
    if (book) mountShareWidget();
    // eslint-disable-next-line
  }, [book]);

  useEffect(() => {
    setHref((window.location as any).currentURL);
  }, []);

  useEffect(() => {
    if (changingFontSize.current) return;

    setWidgetData("share", "show", false);
    if (fontSizePopupShow) setFontSizePopupShow(false);
    if (themePopupShow) setThemePopupShow(false);
    if (scrollTop === 0 && !mobileBarShow) setMobileBarShow(true);
    if (scrollTop !== 0 && mobileBarShow) setMobileBarShow(false);
    // eslint-disable-next-line
  }, [scrollTop]);

  useEffect(() => {
    document.body.style.overflowY =
      (fontSizePopupShow || themePopupShow) && inMobile ? "hidden" : "auto";
  }, [fontSizePopupShow, themePopupShow, inMobile]);

  return inMobile ? (
    // mobile
    <CSSTransition
      in={mobileBarShow}
      classNames="slide-down"
      timeout={150}
      unmountOnExit
    >
      <div className="mobile-operater-wrapper">
        {isCollected ? (
          <div
            className="operater-btn"
            onClick={() => {
              closeAllPopup();
              operateShelf(book);
            }}
          >
            <i className="freelog fl-icon-shoucangxiaoshuoyishoucang"></i>
            <div className="operater-btn-label">移出书架</div>
          </div>
        ) : (
          <div
            className="operater-btn"
            onClick={() => {
              closeAllPopup();
              operateShelf(book);
            }}
          >
            <i className="freelog fl-icon-shoucangxiaoshuo"></i>
            <div className="operater-btn-label">加入书架</div>
          </div>
        )}

        <div
          className="operater-btn"
          onClick={() => {
            closeAllPopup();
            share();
          }}
        >
          <i className="freelog fl-icon-fenxiang"></i>
          <div className="operater-btn-label">分享</div>
        </div>

        <div
          className="operater-btn"
          onClick={() => {
            closeAllPopup();
            setFontSizePopupShow(true);
          }}
        >
          <div className="freelog">A</div>
          <div className="operater-btn-label">字号</div>
        </div>

        <div
          className="operater-btn"
          onClick={() => {
            closeAllPopup();
            setThemePopupShow(true);
          }}
        >
          <i className="freelog fl-icon-beijingyanse"></i>
          <div className="operater-btn-label">背景色</div>
        </div>

        {fontSizePopupShow && (
          <div
            className="operater-popup"
            onClick={() => setFontSizePopupShow(false)}
          >
            <div
              className="fontsize-popup"
              onClick={(e) => e.stopPropagation()}
            >
              <div className="fontsize-label" onClick={() => changeFontSize(0)}>
                A-
              </div>
              <div className="fontsize-value">{fontSize}</div>
              <div className="fontsize-label" onClick={() => changeFontSize(1)}>
                A+
              </div>
            </div>
          </div>
        )}

        {themePopupShow && (
          <div
            className="operater-popup"
            onClick={() => setThemePopupShow(false)}
          >
            <div className="theme-popup" onClick={(e) => e.stopPropagation()}>
              {readerThemeList.map((item) => {
                return (
                  <div
                    className={`theme-btn ${
                      theme.bookColor === item.bookColor && "active"
                    }`}
                    key={item.bookColor}
                    style={{ backgroundColor: item.bookColor }}
                    onClick={() => {
                      setTheme(item);
                      localStorage.setItem("theme", JSON.stringify(item));
                    }}
                  >
                    <i className="freelog fl-icon-xuanzhong"></i>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        <input id="href" className="hidden-input" value={href} readOnly />
      </div>
    </CSSTransition>
  ) : (
    // PC
    <div className="operater-wrapper">
      <div className="operater-btns-box">
        {isCollected ? (
          <OperateBtn
            icon="fl-icon-shoucangxiaoshuoyishoucang"
            onClick={() => {
              closeAllPopup();
              operateShelf(book);
            }}
          />
        ) : (
          <OperateBtn
            icon="fl-icon-shoucangxiaoshuo"
            onClick={() => {
              closeAllPopup();
              operateShelf(book);
            }}
          />
        )}

        <OperateBtn
          icon="fl-icon-fenxiang"
          onClick={() => {
            closeAllPopup();
            setTimeout(() => {
              setWidgetData("share", "show", true);
            }, 0);
          }}
          slot={<div id="share" className="share-wrapper" />}
        />

        <OperateBtn
          text="A"
          onClick={() => {
            closeAllPopup();
            setFontSizePopupShow(true);
          }}
          slot={
            <div
              className={`operater-popup ${
                theme?.type === 1 ? "dark" : "light"
              }`}
              style={{ width: fontSizePopupShow ? "162px" : "0" }}
            >
              <div className="fontsize-label" onClick={() => changeFontSize(0)}>
                A-
              </div>
              <div className="fontsize-value">{fontSize}</div>
              <div className="fontsize-label" onClick={() => changeFontSize(1)}>
                A+
              </div>
            </div>
          }
        />

        <OperateBtn
          icon="fl-icon-beijingyanse"
          onClick={() => {
            closeAllPopup();
            setThemePopupShow(true);
          }}
          slot={
            <div
              className="operater-popup"
              style={{ width: themePopupShow ? "228px" : "0" }}
            >
              {readerThemeList.map((item) => {
                return (
                  <div
                    className={`theme-btn ${
                      theme.bookColor === item.bookColor && "active"
                    }`}
                    key={item.bookColor}
                    style={{ backgroundColor: item.bookColor }}
                    onClick={() => {
                      setTheme(item);
                      localStorage.setItem("theme", JSON.stringify(item));
                    }}
                  >
                    <i className="freelog fl-icon-xuanzhong"></i>
                  </div>
                );
              })}
            </div>
          }
        />

        <BackTop onClick={() => closeAllPopup()}>
          <OperateBtn icon="fl-icon-huidaodingbu" />
        </BackTop>
      </div>
    </div>
  );
};

/** 功能操作按钮 */
const OperateBtn = (props: {
  icon?: string;
  text?: string;
  slot?: any;
  onClick?: (e: any) => void;
}) => {
  const { icon, text, slot, onClick } = props;
  const { theme } = useContext(readerContext);

  return (
    <div
      className={`operate-btn-wrapper ${theme?.type === 1 ? "dark" : "light"}`}
      style={{ backgroundColor: theme?.bookColor }}
      onClick={(e) => e.stopPropagation()}
    >
      {slot}
      {icon && <i className={`freelog ${icon}`} onClick={onClick}></i>}
      {text && (
        <span className="freelog" onClick={onClick}>
          {text}
        </span>
      )}
    </div>
  );
};

// 【4】blog-theme/src/views/reader.vue
<!-- 阅读页 -->

<template>
  <div class="reader-wrapper" :class="{ 'in-mobile': inMobile }" @mouseover="setWidgetData('show', false)">
    <my-header readerHeader />

    <!-- mobile -->
    <div class="mobile-reader-body" v-if="inMobile">
      <div class="article-info">
        <div class="article-title">{{ articleData?.exhibitTitle }}</div>
        <div class="other-info">
          <div class="info-left">
            <div class="info">{{ formatDate(articleData?.createDate) }}</div>
            <div class="divider"></div>
            <div class="info">{{ articleData?.signCount || 0 }}人已签约</div>
          </div>
          <div class="share-btn" @click="share()">
            <span class="share-btn-text"><i class="freelog fl-icon-fenxiang"></i>分享</span>
          </div>
          <input id="href" class="hidden-input" :value="href" readOnly />
        </div>
        <div class="tags">
          <tags :tags="articleData?.tags" />
        </div>
        <div class="article-content">
          <my-loader v-if="contentLoading" />

          <template v-else>
            <div id="markdown" v-if="articleData?.defaulterIdentityType === 0" />

            <template v-else-if="articleData?.defaulterIdentityType">
              <div class="auth-box" v-if="articleData?.defaulterIdentityType !== 4">
                <img class="auth-link-abnormal" src="../assets/images/auth-link-abnormal.png" />
                <div class="auth-link-tip">授权链异常，无法查看</div>
                <div class="home-btn" @click="switchPage('/home')">进入首页</div>
              </div>

              <div class="lock-box" v-else-if="articleData?.defaulterIdentityType === 4 || userData.isLogin === false">
                <img class="lock" src="../assets/images/lock.png" />
                <div class="lock-tip">展品未开放授权，继续浏览请签约并获取授权</div>
                <div class="get-btn" @click="getAuth()">获取授权</div>
              </div>
            </template>
          </template>
        </div>
      </div>

      <div class="recommend">
        <div class="recommend-title">热门推荐</div>
        <div class="article-list">
          <my-article :data="item" v-for="item in recommendList" :key="item.presentableId" />
        </div>
      </div>
    </div>

    <!-- PC -->
    <div class="reader-body" v-if="!inMobile">
      <div class="article-card">
        <div class="title-share">
          <div class="article-title">{{ articleData?.exhibitTitle }}</div>
          <div class="share-btn" @mouseover.stop="setWidgetData('show', true)">
            <span class="share-btn-text" :class="{ active: shareShow }">
              <i class="freelog fl-icon-fenxiang"></i>分享
            </span>

            <div id="share" class="share-wrapper" />
          </div>
        </div>
        <div class="other-info">
          <div class="info">{{ formatDate(articleData?.createDate) }}</div>
          <div class="divider"></div>
          <div class="info">{{ articleData?.signCount || 0 }}人已签约</div>
          <div class="tags">
            <tags :tags="articleData?.tags" />
          </div>
        </div>
        <div class="divider"></div>
        <div class="article-content">
          <my-loader v-if="contentLoading" />

          <template v-else>
            <div id="markdown" v-if="articleData?.defaulterIdentityType === 0" />

            <template v-else-if="articleData?.defaulterIdentityType">
              <div class="auth-box" v-if="articleData?.defaulterIdentityType !== 4">
                <img class="auth-link-abnormal" src="../assets/images/auth-link-abnormal.png" />
                <div class="auth-link-tip">授权链异常，无法查看</div>
                <div class="home-btn" @click="switchPage('/home')">进入首页</div>
              </div>

              <div class="lock-box" v-else-if="articleData?.defaulterIdentityType === 4 || userData.isLogin === false">
                <img class="lock" src="../assets/images/lock.png" />
                <div class="lock-tip">展品未开放授权，继续浏览请签约并获取授权</div>
                <div class="get-btn" @click="getAuth()">获取授权</div>
              </div>
            </template>
          </template>
        </div>
      </div>

      <div class="recommend">
        <div class="recommend-header">
          <div class="recommend-title">热门推荐</div>
          <div class="text-btn" @click="switchPage('/')">更多>></div>
        </div>
        <div class="article-list">
          <my-article :data="item" v-for="item in recommendList" :key="item.presentableId" />
        </div>
      </div>
    </div>

    <my-footer />
  </div>
</template>

<script lang="ts">
import { defineAsyncComponent, onBeforeUnmount, reactive, toRefs, watch } from "vue";
import { useGetList, useMyRouter, useMyScroll } from "../utils/hooks";
import { ExhibitItem } from "@/api/interface";
import {
  addAuth,
  getExhibitAuthStatus,
  getExhibitFileStream,
  getExhibitInfo,
  getExhibitSignCount,
  getSubDep,
  mountWidget,
  getCurrentUrl,
  pushMessage4Task,
} from "@/api/freelog";
import { formatDate } from "@/utils/common";
import { useStore } from "vuex";
import { showToast } from "@/utils/common";

export default {
  name: "reader",

  components: {
    "my-header": defineAsyncComponent(() => import("../components/header.vue")),
    "my-footer": defineAsyncComponent(() => import("../components/footer.vue")),
    tags: defineAsyncComponent(() => import("../components/tags.vue")),
    "my-article": defineAsyncComponent(() => import("../components/article.vue")),
    "my-loader": defineAsyncComponent(() => import("../components/loader.vue")),
  },

  setup() {
    const store = useStore();
    const { query, switchPage, getCurrentPath } = useMyRouter();
    const datasOfGetList = useGetList();
    const { scrollTo } = useMyScroll();

    const data = reactive({
      contentLoading: false,
      articleData: null as ExhibitItem | null,
      contentInfo: null as { content: string; exhibitInfo: ExhibitItem } | null,
      recommendList: [] as ExhibitItem[],
      shareShow: false,
      href: "",
      shareWidget: null as any,
      markdownWidget: null as any,
    });

    const methods = {
      /** 移动端分享 */
      share() {
        const input: any = document.getElementById("href");
        input.select();
        document.execCommand("Copy");
        showToast("链接复制成功～");
        pushMessage4Task({ taskConfigCode: "TS000077", meta: { presentableId: data.articleData?.exhibitId } });
        pushMessage4Task({ taskConfigCode: "TS000804", meta: { presentableId: data.articleData?.exhibitId } });
      },

      /** 获取授权 */
      async getAuth() {
        const { id } = query.value;
        const authResult = await addAuth(id);
        const { status } = authResult;
        if (status === 0) {
          getData();
          refreshAuth();
        }
      },

      /** 通知插件更新数据 */
      setWidgetData(key: string, value: any) {
        if (data.shareWidget && data.shareWidget.getApi().setData) {
          data.shareWidget.getApi().setData(key, value);
        }
      },
    };

    /** 获取文章信息与内容 */
    const getData = async () => {
      data.contentLoading = true;
      const { id } = query.value;

      const [exhibitInfo, signCountData, statusInfo] = await Promise.all([
        getExhibitInfo(id, { isLoadVersionProperty: 1 }),
        getExhibitSignCount(id),
        getExhibitAuthStatus(id),
      ]);
      data.articleData = {
        ...exhibitInfo.data.data,
        signCount: signCountData.data.data[0].count,
        defaulterIdentityType: statusInfo.data.data[0].defaulterIdentityType,
      } as ExhibitItem;

      data.href = getCurrentUrl();
      mountShareWidget();

      if (data.articleData.defaulterIdentityType === 0) {
        // 已签约并且授权链无异常
        const info: any = await getExhibitFileStream(id);
        if (!info) {
          data.contentLoading = false;
          return;
        }

        data.contentInfo = {
          content: info.data,
          exhibitInfo: exhibitInfo.data.data,
        };
      } else if (data.articleData.defaulterIdentityType === 4) {
        // 标的物未签约，自动弹出授权弹窗
        methods.getAuth();
      }

      data.contentLoading = false;
      if (data.articleData.defaulterIdentityType === 0) mountMarkdownWidget();
      await datasOfGetList.getList({ limit: 4 }, true);
      const recommendList = datasOfGetList.listData.value.filter((item: ExhibitItem) => item.exhibitId !== id);
      data.recommendList = recommendList.filter((_: any, index: number) => index < 4);
    };

    /** 刷新授权状态 */
    const refreshAuth = () => {
      const { authIds } = store.state;
      authIds.push(data.articleData?.exhibitId);
      store.commit("setData", { key: "authIds", value: authIds });
    };

    /** 加载分享插件 */
    const mountShareWidget = async () => {
      if (store.state.inMobile) return;

      if (data.shareWidget) await data.shareWidget.unmount();
      const themeData = await getSubDep();
      const widget = themeData.subDep.find((item: any) => item.name === "ZhuC/Freelog插件-展品分享");
      if (!widget) return;
      data.shareWidget = await mountWidget({
        widget,
        container: document.getElementById("share"),
        topExhibitData: themeData,
        config: { exhibit: data.articleData, type: "博客" },
      });
    };

    /** 加载 markdown 插件 */
    const mountMarkdownWidget = async () => {
      const themeData = await getSubDep();
      const widget = themeData.subDep.find((item: any) => item.name === "ZhuC/Freelog插件-markdown解析");
      if (!widget) return;
      data.markdownWidget = await mountWidget({
        widget,
        container: document.getElementById("markdown"),
        topExhibitData: themeData,
        config: { exhibitInfo: data.contentInfo?.exhibitInfo, content: data.contentInfo?.content },
      });
    };

    watch(
      () => query.value,
      () => {
        const path = getCurrentPath();
        if (!path.startsWith("/reader")) return;

        scrollTo(0, "auto");
        data.articleData = null;
        data.contentInfo = null;
        data.recommendList = [];
        getData();
      }
    );

    onBeforeUnmount(async () => {
      await data.shareWidget?.unmount();
      await data.markdownWidget?.unmount();
    });

    getData();

    return {
      ...toRefs(store.state),
      switchPage,
      formatDate,
      ...datasOfGetList,
      ...toRefs(data),
      ...methods,
    };
  },
};
</script>

<style lang="scss" scoped>
.reader-wrapper {
  position: relative;
  min-height: 100vh;
  width: 100%;
  display: flex;
  flex-direction: column;
  align-items: center;
  padding-bottom: 148px;
  box-sizing: border-box;
  background: #fafbfc;

  &.in-mobile {
    background: rgba(0, 0, 0, 0.03);
    padding-bottom: 98px;
  }

  // mobile
  .mobile-reader-body {
    width: 100%;

    .article-info {
      width: 100%;
      min-height: calc(100vh - 64px);
      background: #ffffff;
      padding: 20px;
      box-sizing: border-box;

      .article-title {
        font-size: 20px;
        font-weight: 600;
        color: #222222;
        line-height: 28px;
      }

      .other-info {
        width: 100%;
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-top: 8px;

        .info-left {
          display: flex;
          align-items: center;

          .info {
            font-size: 12px;
            line-height: 18px;
            color: #999999;
          }

          .divider {
            width: 1px;
            height: 14px;
            background: rgba(0, 0, 0, 0.15);
            margin: 0 10px;
          }
        }

        .share-btn {
          position: relative;
          display: flex;
          align-items: center;
          margin-left: 20px;

          .share-btn-text {
            font-size: 12px;
            line-height: 18px;
            color: #999999;

            &:active {
              color: #666666;
            }

            .fl-icon-fenxiang {
              font-size: 14px;
              margin-right: 5px;
            }
          }
        }

        .hidden-input {
          position: absolute;
          z-index: -1;
        }
      }

      .tags {
        margin-top: 12px;
        height: 24px;
        overflow: hidden;
      }

      .article-content {
        font-size: 18px;
        color: #222222;
        line-height: 32px;
        border-top: 1px solid rgba(0, 0, 0, 0.1);
        padding-top: 20px;
        margin-top: 20px;

        .auth-box {
          width: 100%;
          padding: 110px 0;
          display: flex;
          flex-direction: column;
          align-items: center;

          .auth-link-abnormal {
            width: 72px;
            height: 72px;
          }

          .auth-link-tip {
            font-size: 16px;
            color: #222222;
            line-height: 22px;
            margin-top: 30px;
          }

          .home-btn {
            padding: 9px 20px;
            border-radius: 4px;
            font-size: 14px;
            line-height: 20px;
            background-color: #f2f2f2;
            color: #666;
            margin-top: 30px;
            cursor: pointer;

            &:hover {
              opacity: 0.8;
            }

            &:active {
              opacity: 0.6;
            }
          }
        }

        .lock-box {
          width: 100%;
          padding: 110px 0;
          display: flex;
          flex-direction: column;
          align-items: center;

          .lock {
            width: 48px;
            height: 48px;
          }

          .lock-tip {
            font-size: 16px;
            color: #999999;
            line-height: 22px;
            margin-top: 30px;
          }

          .get-btn {
            padding: 9px 20px;
            border-radius: 4px;
            font-size: 14px;
            line-height: 20px;
            font-weight: bold;
            background-color: #2784ff;
            color: #fff;
            margin-top: 30px;
            cursor: pointer;

            &:hover {
              background-color: #529dff;
            }

            &:active {
              background-color: #2376e5;
            }
          }
        }
      }
    }

    .recommend {
      width: 100%;
      padding: 20px 20px 0;
      box-sizing: border-box;
      margin-top: 5px;
      background-color: #fff;

      .recommend-title {
        font-size: 16px;
        font-weight: 600;
        color: #222222;
        line-height: 22px;
      }

      .article-list {
        margin-top: 5px;

        .article-wrapper:last-child {
          border-bottom: none;
        }
      }
    }
  }

  // PC
  .reader-body {
    width: 920px;
    padding-top: 30px;

    .article-card {
      width: 100%;
      min-height: calc(100vh - 130px);
      background: #ffffff;
      box-shadow: 0px 1px 3px 0px rgba(0, 0, 0, 0.1);
      border-radius: 6px;
      padding: 25px 30px;
      box-sizing: border-box;

      .title-share {
        display: flex;
        align-items: center;
        justify-content: space-between;

        .article-title {
          font-size: 24px;
          font-weight: 600;
          color: #222222;
          line-height: 30px;
        }

        .share-btn {
          position: relative;
          display: flex;
          align-items: center;
          margin-left: 30px;
          cursor: pointer;

          .share-btn-text {
            font-size: 14px;
            line-height: 20px;
            color: #222;
            transition: all 0.2s linear;

            &:hover,
            &.active {
              opacity: 0.8;
            }

            &:active {
              opacity: 0.6;
            }

            .fl-icon-fenxiang {
              margin-right: 6px;
            }
          }

          .share-wrapper {
            position: absolute;
            right: 0;
            top: 100%;
          }
        }
      }

      .other-info {
        height: 24px;
        margin-top: 12px;
        display: flex;
        align-items: center;

        .info {
          flex-shrink: 0;
          font-size: 12px;
          color: #999999;
        }

        .divider {
          width: 1px;
          height: 14px;
          background: rgba(0, 0, 0, 0.15);
          margin: 0 10px;
        }

        .tags {
          margin-left: 20px;
          height: 24px;
          overflow: hidden;
        }
      }

      .divider {
        width: 100%;
        height: 1px;
        background-color: rgba(0, 0, 0, 0.1);
        margin: 25px 0;
      }

      .article-content {
        font-size: 14px;
        color: #222222;
        line-height: 24px;

        #markdown {
          position: relative;
          z-index: 0;
        }

        .auth-box {
          width: 100%;
          padding: 110px 0;
          display: flex;
          flex-direction: column;
          align-items: center;

          .auth-link-abnormal {
            width: 72px;
            height: 72px;
          }

          .auth-link-tip {
            font-size: 16px;
            color: #222222;
            line-height: 22px;
            margin-top: 30px;
          }

          .home-btn {
            padding: 9px 20px;
            border-radius: 4px;
            font-size: 14px;
            line-height: 20px;
            background-color: #f2f2f2;
            color: #666;
            margin-top: 30px;
            cursor: pointer;

            &:hover {
              opacity: 0.8;
            }

            &:active {
              opacity: 0.6;
            }
          }
        }

        .lock-box {
          width: 100%;
          padding: 110px 0;
          display: flex;
          flex-direction: column;
          align-items: center;

          .lock {
            width: 48px;
            height: 48px;
          }

          .lock-tip {
            font-size: 16px;
            color: #999999;
            line-height: 22px;
            margin-top: 30px;
          }

          .get-btn {
            padding: 9px 20px;
            border-radius: 4px;
            font-size: 14px;
            line-height: 20px;
            font-weight: bold;
            background-color: #2784ff;
            color: #fff;
            margin-top: 30px;
            cursor: pointer;

            &:hover {
              background-color: #529dff;
            }

            &:active {
              background-color: #2376e5;
            }
          }
        }
      }
    }

    .recommend {
      margin-top: 50px;

      .recommend-header {
        display: flex;
        align-items: center;
        justify-content: space-between;

        .recommend-title {
          font-size: 14px;
          font-weight: 600;
          color: #222222;
          line-height: 20px;
        }

        .text-btn {
          font-size: 14px;
          line-height: 20px;
        }
      }

      .article-list {
        margin-top: 15px;

        .article-wrapper:first-child {
          border-top: 1px solid rgba(0, 0, 0, 0.1);
        }
      }
    }
  }
}
</style>
