// novel-theme/src/screens/shelf/shelf.tsx
import "./shelf.scss";
import { useState, useEffect } from "react";
import { SearchHeader } from "../../components/header/header";
import { useHistory } from "react-router-dom";
import { ExhibitItem } from "../../utils/interface";
import { GetExhibitsListParams, searchExhibits, SearchExhibitsParams } from "../../api/freelog";
import { ShelfNovel } from "../../components/novel/novel";
import { useMyShelf } from "../../utils/hooks";

export const ShelfScreen = () => {
  const { myShelf, operateShelf } = useMyShelf();
  const [shelf, setShelf] = useState<ExhibitItem[]>([]);
  const [keywords, setKeywords] = useState("");
  const getBookList = (params: Partial<GetExhibitsListParams>) => {
    const { keywords = "" } = params;
    setKeywords(keywords);
  };

  const getShelfList = async () => {
    const presentableIds = myShelf.join(",");
    if (!presentableIds) {
      setShelf([]);
      return;
    }

    const queryParams: Partial<SearchExhibitsParams> = { presentableIds };
    const list = await searchExhibits(queryParams);
    setShelf(list.data.data);
  };

  useEffect(() => {
    getShelfList();
    // eslint-disable-next-line
  }, [myShelf]);

  return (
    <div className="shelf-wrapper flex-column align-center">
      <SearchHeader search={getBookList}></SearchHeader>
      <ShelfBody
        shelfList={shelf.filter((item) => item.presentableTitle.includes(keywords))}
        operateShelf={operateShelf}
      />
    </div>
  );
};

const ShelfBody = (props: { shelfList: ExhibitItem[]; operateShelf: (data: ExhibitItem) => void }) => {
  const { shelfList, operateShelf } = props;

  return (
    <div className="content w-100p mw-1412 b-box bg-white">
      <div className="fs-24 mt-40 mb-20">我的书架</div>
      <div className="flex-row flex-wrap">
        {shelfList.map((item) => {
          return (
            <div className="book-box" key={item.presentableId}>
              <ShelfNovel data={item} operateShelf={operateShelf} />
            </div>
          );
        })}

        <AddBook />
      </div>
    </div>
  );
};

const AddBook = () => {
  const history = useHistory();

  return (
    <div className="add-book-box text-center brs-6 transition cur-pointer" onClick={() => history.push(`/`)}>
      <img
        className="w-32 h-32"
        src="https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/image/shelf_last_add.fe952d0f.png"
        alt=""
      />
    </div>
  );
};

// comic-theme/src/views/shelf.vue
<template>
  <div class="shelf-wrapper flex-column align-center">
    <my-header :getList="search" />

    <div class="content w-100p mw-1412 b-box">
      <div class="fs-24 mt-40 mb-20">我的漫画</div>

      <div class="flex-row flex-wrap">
        <shelf-comic
          class="book-box mb-44"
          :data="item"
          :operateShelf="operateShelf"
          v-for="item in shelf"
          :key="item.presentableId"
        ></shelf-comic>

        <div
          class="add-book-box p-relative shrink-0 mb-44 brs-4 transition cur-pointer"
          @click="switchPage('/')"
          title="去添加漫画"
        >
          <div class="w-100p h-0 pb-75p text-center">
            <img
              class="p-absolute w-32 h-32 t-50p mt--16"
              src="https://weread-1258476243.file.myqcloud.com/web/wrwebnjlogic/image/shelf_last_add.fe952d0f.png"
              alt="加入书架"
            />
          </div>
        </div>
      </div>
    </div>
  </div>
</template>

<script lang="ts">
import { computed, defineAsyncComponent, ref } from "@vue/runtime-core";
import { useMyRouter, useMyShelf } from "../utils/hooks";
import { CollectExhibitItem } from "../utils/interface";

export default {
  name: "shelf",

  components: {
    "my-header": defineAsyncComponent(() => import("../components/header.vue")),
    "shelf-comic": defineAsyncComponent(() => import("../components/shelf-comic.vue")),
  },

  setup() {
    const { switchPage } = useMyRouter();
    const { myShelf, operateShelf } = useMyShelf();
    const searchKey = ref("");
    const shelf = computed(() => {
      return myShelf.value.filter((item: CollectExhibitItem) => item.presentableTitle.includes(searchKey.value));
    });

    const search = (params: { keywords: string }, init: boolean) => {
      if (!init) return [];

      searchKey.value = params.keywords || "";
    };

    return {
      shelf,
      search,
      switchPage,
      operateShelf,
    };
  },
};
</script>

<style lang="scss" scoped>
.shelf-wrapper {
  min-height: 100vh;
  background-image: url(../assets/image/bg.png);

  .content {
    padding: 0 40px;

    .book-box {
      width: 18%;
      margin-right: 2%;
    }

    .add-book-box {
      width: 18%;
      margin-right: 0 !important;
      background-color: #edeeef;

      &:hover {
        background-color: #e0e0e0;
      }
    }
  }
}

@media (max-width: 900px) {
  .content {
    padding: 0 20px;

    .book-box,
    .add-book-box {
      width: 31% !important;
      margin-right: 2% !important;
    }
  }
}

@media (max-width: 600px) {
  .content {
    .book-box,
    .add-book-box {
      width: 46% !important;
      margin-right: 4% !important;
    }
  }
}
</style>
