// theme/【3】gallery-theme/src/components/login-btn.vue
<!-- 移动端登录/注册按钮 -->

<template>
  <div
    class="login-btn-wrapper main-btn mobile"
    :class="{ show: show && inMobile }"
    :style="{ boxShadow: `0px 2px 10px 0px ${theme.deriveColor}40` }"
    @click="callLogin()"
  >
    登录 / 注册
  </div>
</template>

<script lang="ts">
import { useStore } from "vuex";
import { callLogin } from "@/api/freelog";
import { reactive, watch } from "vue";
import { toRefs } from "vue";

export default {
  name: "LoginBtn",

  setup() {
    const store = useStore();
    const data = reactive({
      show: false,
    });

    watch(
      () => store.state.userData,
      (cur) => {
        data.show = !cur.isLogin;
      },
      { immediate: true }
    );

    return {
      callLogin,
      ...toRefs(store.state),
      ...toRefs(data),
    };
  },
};
</script>

<style lang="scss" scoped>
.login-btn-wrapper {
  position: fixed;
  bottom: 50px;
  left: 50%;
  transform: translateX(-50%);
  width: 240px;
  height: 60px;
  border-radius: 60px;
  font-size: 16px;
  font-weight: 600;
  color: #ffffff;
  box-shadow: 0px 2px 10px 0px rgba(39, 132, 255, 0.4);
  z-index: 100;
  display: none;

  &.show {
    display: flex;
    align-items: center;
    justify-content: center;
  }
}
</style>

// 【1】novel-theme/src/components/login-btn/login-btn.tsx
import { useContext } from "react";
import { callLogin } from "../../api/freelog";
import { globalContext } from "../../router";
import "./login-btn.scss";

/** 移动端登录/注册按钮 */
export const LoginBtn = () => {
  const { userData, inMobile, theme } = useContext(globalContext);

  return (
    <div
      className={`login-btn-wrapper main-btn mobile 
      ${(userData?.isLogin || !inMobile) && "hidden"}`}
      style={{ boxShadow: `0px 2px 10px 0px ${theme.deriveColor}40` }}
      onClick={() => callLogin()}
    >
      登录 / 注册
    </div>
  );
};
