// 【2】comic-theme/src/views/detail.vue
<!-- 详情页 -->

<template>
  <div class="detail-wrapper">
    <my-header />

    <!-- mobile -->
    <div
      class="mobile-content"
      :class="` ${comicInfo?.articleInfo?.status === 2 && 'freeze-exhibit'}`"
      v-if="inMobile"
    >
      <template v-if="comicInfo?.articleInfo?.status">
        <div class="freeze-exhibit">
          <div class="icon">
            <i
              class="freelog fl-icon-a-yichang_wendangbokexiaoshuoziyuan freeze"
              :class="{ light: theme === 'light', dark: theme === 'dark' }"
            ></i>
          </div>
          <span className="exceptional-text"> 此作品因违规无法访问 </span>
        </div></template
      >
      <template v-else>
        <!-- 已下架、授权链异常 顶部提示窗  -->
        <div
          className="exceptional-message"
          v-if="
            comicInfo.onlineStatus === 0 ||
            ![0, 4, undefined].includes(comicInfo?.defaulterIdentityType)
          "
        >
          {{ comicInfo.onlineStatus === 0 ? "作品已下架，无法访问" : "作品异常，无法访问" }}
        </div>

        <div
          class="auth-link-abnormal-tip"
          v-if="
            comicInfo.defaulterIdentityType && ![0, 4].includes(comicInfo.defaulterIdentityType)
          "
        >
          <img class="auth-link-abnormal" src="../assets/images/auth-link-abnormal.png" />
          <div class="tip-text">作品异常，无法访问</div>
        </div>

        <!-- 漫画信息 -->
        <div class="comic-info">
          <div class="comic-base-info">
            <div class="comic-cover">
              <div>
                <img
                  class="comic-cover-image"
                  :src="comicInfo?.coverImages[0]"
                  :alt="comicInfo?.exhibitTitle"
                  v-if="comicInfo?.coverImages"
                />
                <div v-if="comicInfo.onlineStatus === 0" class="offline">已下架</div>
              </div>
            </div>

            <div class="comic-content">
              <div class="content-top">
                <div class="comic-name">{{ comicInfo?.exhibitTitle }}</div>

                <div class="comic-author">
                  {{ comicInfo?.articleInfo?.articleOwnerName }}
                </div>

                <div class="tags">
                  <tags :tags="comicInfo?.tags" />
                </div>
              </div>

              <div class="content-bottom">
                <div class="sign-count">{{ comicInfo?.signCount }}人签约</div>
                <div class="share-btn" @click="share()">
                  <span class="share-btn-text">
                    <i class="freelog fl-icon-fenxiang"></i>
                    分享给更多人
                  </span>
                </div>
                <input id="href" class="hidden-input" :value="href" readOnly />
              </div>
            </div>
          </div>

          <div class="comic-date-info">
            <div class="date-info">创建时间：{{ formatDate(comicInfo?.createDate) }}</div>

            <div class="date-info">最近更新：{{ formatDate(comicInfo?.updateDate) }}</div>
          </div>

          <div class="operate-btns">
            <div
              class="btn main-btn mobile"
              :class="{
                disabled:
                  ![0, 4].includes(comicInfo.defaulterIdentityType ?? -1) ||
                  comicInfo.onlineStatus === 0 ||
                  (comicInfo.articleInfo.articleType === 2 && !listData.length)
              }"
              @click="handleToReader"
            >
              立即阅读
            </div>
            <div
              class="btn"
              :class="isCollected ? 'delete' : 'collect-btn mobile'"
              @click="operateShelf(comicInfo)"
            >
              {{ isCollected ? "取消收藏" : "加入收藏" }}
            </div>
          </div>
        </div>

        <div class="divider"></div>

        <!-- 漫画简介 -->
        <div class="comic-intro">
          <div class="intro-title">内容简介</div>

          <div
            class="intro"
            :class="introState === 1 ? 'fold' : 'unfold'"
            v-if="comicInfo?.exhibitIntro"
          >
            <div ref="introContent" class="intro-content">
              {{ comicInfo?.exhibitIntro }}
            </div>

            <div class="view-all-btn" @click="introState = 3" v-if="introState === 1">
              ...查看全部
            </div>
          </div>
          <div class="no-intro-tip" v-else>暂无简介</div>
        </div>

        <div class="divider" v-if="comicInfo?.articleInfo?.articleType === 2"></div>

        <!-- 目录 -->
        <template v-if="comicInfo?.articleInfo?.articleType === 2">
          <div class="comic-catalogue" v-if="listData.length">
            <div class="title-container">
              <span class="title">目录</span>
            </div>

            <div class="sub-directory-container">
              <div
                class="sub"
                :class="
                  (![0, 4].includes(item.defaulterIdentityType) || comicInfo.onlineStatus === 0) &&
                  'disabled'
                "
                v-for="item in listData"
                :key="item.itemId"
                @click="
                  switchPage('/reader', {
                    id: comicInfo?.exhibitId,
                    collection: true,
                    subId: item.itemId
                  })
                "
              >
                <span class="sub-title">{{ item.itemTitle }}</span>

                <img
                  v-if="item.articleInfo?.status === 2"
                  class="freeze-lock"
                  src="../assets/images/freeze.png"
                  alt="封禁"
                />
                <div v-else-if="comicInfo.onlineStatus === 0" className="offline-lock">已下架</div>
                <img
                  v-else-if="![0, 4].includes(item.defaulterIdentityType)"
                  class="auth-lock"
                  src="../assets/images/auth-link-abnormal.png"
                  alt="授权链异常"
                />
                <img
                  v-else-if="item.defaulterIdentityType === 4"
                  class="sub-lock"
                  src="../assets/images/mini-lock.png"
                  alt="未授权"
                />
                <img v-else src="../assets/images/right-arrow.png" alt="" />
              </div>
            </div>

            <div className="tip no-more" v-if="listData.length === total">— 已加载全部章节 —</div>
          </div>

          <div v-else class="comic-catalogue">
            <div class="title-container">
              <span class="title">目录</span>
            </div>
            <div class="no-update">未更新章节，暂时无法阅读</div>
          </div>
        </template>

        <login-btn />
      </template>
    </div>

    <!-- PC -->
    <div
      class="content"
      :class="` ${comicInfo?.articleInfo?.status === 2 && 'freeze-exhibit'}`"
      v-if="!inMobile"
    >
      <template v-if="comicInfo?.articleInfo?.status === 2">
        <div class="freeze-exhibit">
          <div class="icon">
            <i
              class="freelog fl-icon-a-yichang_wendangbokexiaoshuoziyuan freeze"
              :class="{ light: theme === 'light', dark: theme === 'dark' }"
            ></i>
          </div>
          <span className="exceptional-text"> 此作品因违规无法访问 </span>
        </div>
      </template>

      <template v-else>
        <!-- 已下架、授权链异常 顶部提示窗  -->
        <div
          className="exceptional-message"
          v-if="
            comicInfo.onlineStatus === 0 ||
            ![0, 4, undefined].includes(comicInfo?.defaulterIdentityType)
          "
        >
          {{ comicInfo.onlineStatus === 0 ? "作品已下架，无法访问" : "作品异常，无法访问" }}
        </div>

        <div
          class="auth-link-abnormal-tip"
          v-if="
            comicInfo.defaulterIdentityType && ![0, 4].includes(comicInfo.defaulterIdentityType)
          "
        >
          <img class="auth-link-abnormal" src="../assets/images/auth-link-abnormal.png" />
          <div class="tip-text">作品异常，无法访问</div>
        </div>

        <div class="content-box">
          <!-- 漫画信息 -->
          <div class="comic-info">
            <div class="comic-cover">
              <div>
                <img
                  class="comic-cover-image"
                  :src="comicInfo?.coverImages[0]"
                  :alt="comicInfo?.exhibitTitle"
                  v-if="comicInfo?.coverImages"
                />
                <div v-if="comicInfo.onlineStatus === 0" class="offline">已下架</div>
              </div>
            </div>

            <div class="comic-content">
              <div class="comic-name" :title="comicInfo?.exhibitTitle">
                {{ comicInfo?.exhibitTitle }}
              </div>

              <div class="comic-author">
                {{ comicInfo?.articleInfo?.articleOwnerName }}
              </div>

              <div class="tags">
                <tags :tags="comicInfo?.tags" />
              </div>

              <div class="create-date">创建时间：{{ formatDate(comicInfo?.createDate) }}</div>

              <div class="update-date">最近更新：{{ formatDate(comicInfo?.updateDate) }}</div>

              <div class="btns-box">
                <div class="operate-btns">
                  <div
                    class="btn main-btn"
                    :class="{
                      disabled:
                        ![0, 4].includes(comicInfo.defaulterIdentityType ?? -1) ||
                        comicInfo.onlineStatus === 0 ||
                        (comicInfo.articleInfo.articleType === 2 && !listData.length)
                    }"
                    @click="handleToReader"
                  >
                    立即阅读
                  </div>
                  <div
                    class="btn"
                    :class="isCollected ? 'warning-btn' : 'collect-btn'"
                    @click="operateShelf(comicInfo)"
                  >
                    {{ isCollected ? "取消收藏" : "加入收藏" }}
                  </div>
                </div>

                <div class="other-btns">
                  <div class="sign-count">{{ comicInfo?.signCount }}人签约</div>
                  <div
                    class="share-btn"
                    @mouseenter.stop="setShareWidgetShow(true)"
                    @mouseleave.stop="setShareWidgetShow(false)"
                  >
                    <span class="share-btn-text" :class="{ active: shareShow }">
                      <i class="freelog fl-icon-fenxiang"></i>
                      分享给更多人
                    </span>

                    <div id="share" class="share-wrapper" />
                  </div>
                </div>
              </div>
            </div>
          </div>

          <!-- 漫画简介 -->
          <div
            class="comic-intro"
            :class="comicInfo?.articleInfo?.articleType === 2 && 'need-border'"
          >
            <div class="intro-title">内容简介</div>
            <div
              class="intro"
              :class="introState === 1 ? 'fold' : 'unfold'"
              v-if="comicInfo?.exhibitIntro"
            >
              <div ref="introContent" class="intro-content">
                {{ comicInfo?.exhibitIntro }}
              </div>

              <div class="view-all-btn" @click="introState = 3" v-if="introState === 1">
                ...查看全部
              </div>
            </div>
            <div class="no-intro-tip" v-else>暂无简介</div>
          </div>

          <!-- 目录 -->
          <template v-if="comicInfo?.articleInfo?.articleType === 2">
            <div class="comic-catalogue" v-if="listData.length">
              <div class="title-container">
                <span class="title">目录</span>
                <span class="count">({{ total }}话)</span>

                <div class="sort" @click="handleSort">
                  <span>{{ sortOrder === "asc" ? "正序" : "倒序" }}</span>
                  <span class="triangle" :class="sortOrder === 'asc' ? 'asc' : 'desc'"></span>
                </div>
              </div>

              <div class="sub-directory-container">
                <div
                  class="sub"
                  :class="
                    (![0, 4].includes(item.defaulterIdentityType) ||
                      comicInfo.onlineStatus === 0) &&
                    'disabled'
                  "
                  v-for="item in listData"
                  :key="item.itemId"
                  @click="
                    switchPage('/reader', {
                      id: comicInfo?.exhibitId,
                      collection: true,
                      subId: item.itemId
                    })
                  "
                >
                  <span class="sub-title">{{ item.itemTitle }}</span>
                  <img
                    v-if="item.articleInfo?.status === 2"
                    class="freeze-lock"
                    src="../assets/images/freeze.png"
                    alt="封禁"
                  />
                  <div v-else-if="comicInfo.onlineStatus === 0" className="offline-lock">
                    已下架
                  </div>
                  <img
                    v-else-if="![0, 4].includes(item.defaulterIdentityType)"
                    class="auth-lock"
                    src="../assets/images/auth-link-abnormal.png"
                    alt="授权链异常"
                  />
                  <img
                    v-else-if="item.defaulterIdentityType === 4"
                    class="sub-lock"
                    src="../assets/images/mini-lock.png"
                    alt="未授权"
                  />
                </div>
              </div>

              <div className="tip no-more" v-if="listData.length === total">— 已加载全部章节 —</div>
            </div>

            <div v-else class="comic-catalogue">
              <div class="title-container">
                <span class="title">目录</span>
              </div>
              <div class="no-update">未更新章节，暂时无法阅读</div>
            </div>
          </template>
        </div>
      </template>
    </div>

    <my-footer />

    <theme-entrance />
  </div>
</template>

<script lang="ts">
import { onBeforeUnmount } from "vue";
import { useStore } from "vuex";
import { defineAsyncComponent, reactive, ref, toRefs, watch } from "@vue/runtime-core";
import { WidgetController, freelogApp } from "freelog-runtime";
import { useMyRouter, useMyShelf, useMyScroll } from "@/utils/hooks";
import { formatDate, showToast } from "@/utils/common";
import { ExhibitItem, CollectionList } from "@/api/interface";
import { State } from "@/store/index";

export default {
  name: "detail",

  components: {
    "my-header": defineAsyncComponent(() => import("../components/header.vue")),
    "my-footer": defineAsyncComponent(() => import("../components/footer.vue")),
    "login-btn": defineAsyncComponent(() => import("../components/login-btn.vue")),
    "theme-entrance": defineAsyncComponent(() => import("../components/theme-entrance.vue")),
    tags: defineAsyncComponent(() => import("../components/tags.vue"))
  },

  setup() {
    const store = useStore<State>();
    const { query, switchPage, routerBack } = useMyRouter();
    const { scrollTop, clientHeight, scrollHeight } = useMyScroll();
    const { id } = query.value;
    const { isCollected, operateShelf } = useMyShelf(id);
    const introContent = ref<any>();
    const sortOrder = ref<string>("asc"); // 默认排序为正序

    const data = reactive({
      comicInfo: {} as ExhibitItem,
      shareShow: false,
      introState: 0,
      href: "",
      shareWidget: null as WidgetController | null
    });

    const collectionData = reactive({
      listData: [] as CollectionList[],
      total: 0,
      skip: 0
    });

    const methods = {
      /** 移动端分享 */
      share() {
        const input: any = document.getElementById("href");
        input.select();
        document.execCommand("Copy");
        showToast("链接复制成功～");
        // freelogApp.pushMessage4Task({ taskConfigCode: "TS000077", meta: { presentableId: data.comicInfo.exhibitId } });
      },

      /** 控制分享弹窗显示 */
      setShareWidgetShow(value: boolean) {
        data.shareWidget?.setData({ show: value });
      },

      /** 立即阅读 */
      async handleToReader() {
        if (collectionData.listData.length) {
          try {
            const res = await freelogApp.getUserData("comicLastViewedHistory");
            const lastViewed = res?.data?.data || [];
            const index = lastViewed.findIndex(
              (i: { id: string }) => i.id === data.comicInfo?.exhibitId
            );
            const subId = lastViewed[index]?.subId;
            switchPage("/reader", {
              id: data.comicInfo?.exhibitId,
              collection: true,
              subId: subId || collectionData.listData[0].itemId
            });
          } catch (error) {
            console.error("Error fetching user data", error);
          }
        } else {
          switchPage("/reader", { id: data.comicInfo?.exhibitId });
        }
      },

      /**
       * 切换正序，倒序
       */
      handleSort() {
        // 切换排序顺序
        sortOrder.value = sortOrder.value === "asc" ? "desc" : "asc";

        // 使用排序函数
        const compare = (a: any, b: any) => {
          return sortOrder.value === "asc" ? a.sortId - b.sortId : b.sortId - a.sortId;
        };

        // 根据当前排序顺序更新数据
        collectionData.listData.sort(compare);
      }
    };

    /** 获取漫画信息 */
    const getComicInfo = async (id: string) => {
      const [exhibitInfo, signCountData, statusInfo] = await Promise.all([
        freelogApp.getExhibitInfo(id, { isLoadVersionProperty: 1 }),
        freelogApp.getExhibitSignCount(id),
        freelogApp.getExhibitAuthStatus(id)
      ]);

      const articleType = exhibitInfo.data.data.articleInfo.articleType;
      if (articleType === 2) {
        getCollectionList(true);

        sortOrder.value =
          (exhibitInfo.data.data.versionInfo?.exhibitProperty?.catalogueProperty as any)
            ?.collection_sort_list === "collection_sort_descending"
            ? "desc"
            : "asc";
      }

      const { count } = signCountData.data.data[0];
      const { defaulterIdentityType = -1 } = statusInfo.data.data[0];
      data.comicInfo = {
        ...exhibitInfo.data.data,
        signCount: count,
        defaulterIdentityType
      };
      data.href = freelogApp.getCurrentUrl();

      mountShareWidget();
    };

    /** 加载分享插件 */
    const mountShareWidget = async () => {
      if (store.state.inMobile) return;

      const container = document.getElementById("share");
      if (!container) return;

      const subDeps = await freelogApp.getSelfDependencyTree();
      const widgetData = subDeps.find(item => item.articleName === "ZhuC/Freelog插件-展品分享");
      if (!widgetData) return;

      const { articleId, parentNid, nid } = widgetData;
      const topExhibitId = freelogApp.getTopExhibitId();

      const params = {
        articleId,
        parentNid,
        nid,
        topExhibitId,
        container,
        renderWidgetOptions: {
          data: { exhibit: data.comicInfo, type: "漫画", routerType: "detail" }
        }
        // widget_entry: "https://localhost:8201",
      };
      data.shareWidget = await freelogApp.mountArticleWidget(params);
    };

    const getCollectionList = async (init = false) => {
      let { total, listData, skip } = collectionData;

      if (!init && listData.length >= total) return;
      skip = init ? 0 : collectionData.skip + 50;

      const subList = await (freelogApp as any).getCollectionSubList(id, {
        skip,
        limit: 50
      });
      const { dataList, totalItem } = subList.data.data;
      collectionData.total = totalItem;

      if (dataList.length !== 0) {
        const ids = dataList.map((item: any) => item.itemId).join();
        const statusInfo = await (freelogApp as any).getCollectionSubAuth(id, { itemIds: ids });
        if (statusInfo.data.data) {
          (dataList as CollectionList[]).forEach(item => {
            const index = statusInfo.data.data.findIndex(
              (resultItem: { itemId: string }) => resultItem.itemId === item.itemId
            );
            if (index !== -1) {
              item.defaulterIdentityType = statusInfo.data.data[index].defaulterIdentityType;
            }
          });
        }
      }
      collectionData.listData = init ? dataList : [...listData, ...dataList];
    };

    watch(
      () => introContent.value,
      () => {
        const introHeight = introContent.value.clientHeight;
        const foldHeight = store.state.inMobile ? 120 : 60;
        if (introHeight > foldHeight) data.introState = 1;
      }
    );

    watch(
      () => scrollTop.value,
      cur => {
        if (cur + clientHeight.value !== scrollHeight.value) return;
        getCollectionList();
      }
    );

    onBeforeUnmount(async () => {
      await data.shareWidget?.unmount();
    });

    getComicInfo(id);

    return {
      formatDate,
      ...toRefs(store.state),
      switchPage,
      routerBack,
      isCollected,
      operateShelf,
      introContent,
      ...toRefs(data),
      ...toRefs(collectionData),
      ...methods,
      sortOrder
    };
  }
};
</script>

<style lang="scss" scoped>
@import "@/assets/css/detail";
</style>

// 【1】novel-theme/src/screens/detail/detail.tsx
import React, { useContext, useRef, useState, useEffect, useCallback } from "react";
import { freelogApp } from "freelog-runtime";
import { globalContext } from "../../router";
import { Header } from "../../components/header/header";
import { Tags } from "../../components/tags/tags";
import { Footer } from "../../components/footer/footer";
import { ThemeEntrance } from "../../components/theme-entrance/theme-entrance";
import { LoginBtn } from "../../components/login-btn/login-btn";
import { showToast } from "../../components/toast/toast";

import { CollectionList, ExhibitItem } from "../../api/interface";
import { formatDate, getUrlParams } from "../../utils/common";
import { useMyHistory, useMyScroll, useMyShelf } from "../../utils/hooks";
import AuthLinkAbnormal from "../../assets/images/auth-link-abnormal.png";
import Freeze from "../../assets/images/freeze.png";
import Lock from "../../assets/images/mini-lock.png";
import RightArrow from "../../assets/images/right-arrow.png";

import "./detail.scss";

const detailContext = React.createContext<any>({});

/** 详情页 */
export const DetailScreen = (props: any) => {
  const { scrollTop, clientHeight, scrollHeight } = useMyScroll();
  const { id } = getUrlParams(props.location.search);
  const [novel, setNovel] = useState<ExhibitItem | null>(null);
  const [total, setTotal] = useState<number>(0);
  const skip = useRef(0);
  const [sortOrder, setSortOrder] = useState("asc");

  // 获取合集下的单品列表
  const getCollectionList = useCallback(
    async (init = false) => {
      try {
        if (!init && (novel?.collectionList?.length ?? 0) >= total) {
          return;
        }

        skip.current = init ? 0 : skip.current + 50;

        const subList = await (freelogApp as any).getCollectionSubList(id, {
          skip: skip.current,
          limit: 50
        });
        const { dataList, totalItem } = subList.data.data;
        setTotal(totalItem);

        if (dataList.length !== 0) {
          const ids = dataList.map((item: any) => item.itemId).join();
          const statusInfo = await (freelogApp as any).getCollectionSubAuth(id, { itemIds: ids });
          if (statusInfo.data.data) {
            (dataList as ExhibitItem[]).forEach((item: any) => {
              const index = statusInfo.data.data.findIndex(
                (resultItem: { itemId: string }) => resultItem.itemId === item.itemId
              );
              if (index !== -1) {
                item.defaulterIdentityType = statusInfo.data.data[index].defaulterIdentityType;
              }
            });
          }

          setNovel((pre: any) => ({
            ...pre,
            collectionList: pre?.collectionList ? [...pre?.collectionList, ...dataList] : dataList
          }));
        }
      } catch (error) {
        console.error("Failed to get collection list", error);
      }
    },
    [id, novel]
  );

  /** 获取小说信息 */
  const getNovelInfo = useCallback(async () => {
    try {
      const [exhibitInfo, signCountData, statusInfo] = await Promise.all([
        freelogApp.getExhibitInfo(id, { isLoadVersionProperty: 1 }),
        freelogApp.getExhibitSignCount(id),
        freelogApp.getExhibitAuthStatus(id)
      ]);

      const articleType = exhibitInfo.data.data.articleInfo.articleType;
      if (articleType === 2) {
        getCollectionList(true);
        setSortOrder(
          (novel?.versionInfo?.exhibitProperty?.catalogueProperty as any)?.collection_sort_list ===
            "collection_sort_descending"
            ? "desc"
            : "asc"
        );
      }

      const bookInfo = {
        ...exhibitInfo.data.data,
        signCount: signCountData.data.data[0]?.count ?? 0,
        defaulterIdentityType: statusInfo.data.data[0]?.defaulterIdentityType ?? null
      };

      setNovel(bookInfo);
    } catch (error) {
      console.error("Failed to get novel info", error);
    }
  }, [id]);

  useEffect(() => {
    document.documentElement.scrollTop = 0;
    document.body.scrollTop = 0;
    getNovelInfo();
  }, []);

  useEffect(() => {
    if (novel?.collectionList?.length && scrollTop + clientHeight === scrollHeight) {
      getCollectionList(false);
    }
  }, [scrollTop, clientHeight, scrollHeight]);

  return (
    <detailContext.Provider value={{ novel, setNovel, sortOrder, setSortOrder }}>
      <div className="detail-wrapper">
        <Header />
        <DetailBody total={total} />
        <Footer />
        <LoginBtn />
        <ThemeEntrance />
      </div>
    </detailContext.Provider>
  );
};

/** 详情页主体内容 */
const DetailBody = (props: { total: number }) => {
  const { total } = props;
  const { inMobile, userData } = useContext(globalContext);
  const { novel, setNovel, sortOrder, setSortOrder } = useContext(detailContext);
  const collectionList = novel?.collectionList;
  const { isCollected, operateShelf } = useMyShelf(novel?.exhibitId);
  const history = useMyHistory();
  const introContent = useRef<any>();
  const shareWidget = useRef<any>();
  const [introState, setIntroState] = useState(0);
  const [href, setHref] = useState("");
  // const [sortOrder, setSortOrder] = useState("asc");

  /** 移动端分享 */
  const share = () => {
    // 复制链接
    const input: any = document.getElementById("href");
    input.select();
    document.execCommand("Copy");
    showToast("链接复制成功～");
    // freelogApp.pushMessage4Task({ taskConfigCode: "TS000077", meta: { presentableId: novel.exhibitId } });
  };

  /** 加载分享插件 */
  const mountShareWidget = async () => {
    if (inMobile) return;

    const container = document.getElementById("share");
    if (!container) return;

    const subDeps = await freelogApp.getSelfDependencyTree();
    const widgetData = subDeps.find(item => item.articleName === "ZhuC/Freelog插件-展品分享");
    if (!widgetData) return;

    const { articleId, parentNid, nid } = widgetData;
    const topExhibitId = freelogApp.getTopExhibitId();

    const params = {
      articleId,
      parentNid,
      nid,
      topExhibitId,
      container,
      renderWidgetOptions: {
        data: { exhibit: novel, type: "小说", routerType: "detail" }
      }
      // widget_entry: "https://localhost:8201",
    };
    shareWidget.current = await freelogApp.mountArticleWidget(params);
  };

  /** 控制分享弹窗显示 */
  const setShareWidgetShow = (value: boolean) => {
    shareWidget.current?.setData({ show: value });
  };

  /**
   * 切换正序，倒序
   */
  const handleSort = () => {
    // 切换排序顺序
    setSortOrder(sortOrder === "asc" ? "desc" : "asc");
  };

  useEffect(() => {
    // 使用排序函数
    const compare = (a: any, b: any) => {
      return sortOrder === "asc" ? a.sortId - b.sortId : b.sortId - a.sortId;
    };

    if (collectionList && collectionList.length) {
      setNovel((pre: any) => ({
        ...pre,
        collectionList: collectionList.sort(compare)
      }));
    }
  }, [sortOrder]);

  useEffect(() => {
    setHref(freelogApp.getCurrentUrl());

    return () => {
      if (inMobile) return;
      (async function unmountWidget() {
        await shareWidget.current?.unmount();
      })();
    };
    // eslint-disable-next-line
  }, []);

  useEffect(() => {
    const introHeight = introContent.current?.clientHeight;
    const foldHeight = inMobile ? 120 : 60;
    if (introHeight > foldHeight) setIntroState(1);
    if (novel) mountShareWidget();
    // eslint-disable-next-line
  }, [novel, inMobile]);

  return inMobile ? (
    // mobile
    <div className={`mobile-content ${novel?.articleInfo.status === 2 && "freeze-exhibit"}`}>
      {novel?.articleInfo.status === 2 ? (
        <div className="freeze-exhibit">
          <div className="icon">
            <i className="freelog fl-icon-a-yichang_tupianshipinmanhuaziyuan freeze"> </i>
          </div>
          <span className="exceptional-text"> 此作品因违规无法访问 </span>
        </div>
      ) : (
        novel && (
          <>
            {/* 已下架、授权链异常 顶部提示窗 */}
            {(novel.onlineStatus === 0 || ![0, 4].includes(novel.defaulterIdentityType)) && (
              <div className="exceptional-message">
                {novel.onlineStatus === 0 ? "作品已下架，无法访问" : "作品异常，无法访问"}
              </div>
            )}

            {/* 授权链异常提示 */}
            {![0, 4].includes(novel.defaulterIdentityType) && (
              <div className="auth-link-abnormal-tip">
                <img className="auth-link-abnormal" src={AuthLinkAbnormal} alt="授权链异常" />
                <div className="tip-text">授权链异常，无法查看</div>
              </div>
            )}
            {/* 书籍信息 */}
            <div className="novel-info">
              <div className="novel-base-info">
                <div className="novel-cover">
                  <>
                    <img
                      className="novel-cover-image"
                      src={novel.coverImages[0]}
                      alt={novel.exhibitTitle}
                    />
                    {novel.onlineStatus === 0 && <div className="offline">已下架</div>}
                  </>
                </div>

                <div className="novel-content">
                  <div className="content-top">
                    <div className="novel-name">{novel.exhibitTitle}</div>

                    <div className="novel-author">{novel.articleInfo.articleOwnerName}</div>

                    <div className="tags">
                      <Tags data={novel.tags || []} />
                    </div>
                  </div>

                  <div className="content-bottom">
                    <div className="sign-count">{novel.signCount}人签约</div>
                    <div className="share-btn" onClick={() => share()}>
                      <span className="share-btn-text">
                        <i className="freelog fl-icon-fenxiang"></i>
                        分享给更多人
                      </span>
                    </div>
                    <input id="href" className="hidden-input" value={href} readOnly />
                  </div>
                </div>
              </div>

              <div className="novel-date-info">
                <div className="date-info">创建时间：{formatDate(novel.createDate)}</div>

                <div className="date-info">最近更新：{formatDate(novel.updateDate)}</div>
              </div>

              <div className="operate-btns">
                <div
                  className={`btn main-btn mobile
                  ${
                    (![0, 4].includes(novel.defaulterIdentityType) || novel.onlineStatus === 0) &&
                    "disabled"
                  }`}
                  onClick={async () => {
                    if (collectionList?.length) {
                      const res = await freelogApp.getUserData("novelLastViewedHistory");
                      const lastViewed = res?.data?.data || [];
                      const index = lastViewed.findIndex(
                        (i: { id: string }) => i.id === novel.exhibitId
                      );
                      const subId = lastViewed[index]?.subId;

                      history.switchPage(
                        `/reader?collection=${true}&id=${novel.exhibitId}&subId=${
                          subId || collectionList[0].itemId
                        }`
                      );
                    } else {
                      history.switchPage(`/reader?id=${novel.exhibitId}`);
                    }
                  }}
                >
                  立即阅读
                </div>
                <div
                  className={`btn ${isCollected ? "delete" : "collect-btn mobile"}`}
                  onClick={() => operateShelf(novel)}
                >
                  {isCollected ? "移出书架" : "加入书架"}
                </div>
              </div>
            </div>
            {/* 书籍简介 */}
            <div className="novel-intro">
              <div className="intro-title">内容简介</div>

              {novel.exhibitIntro ? (
                <div className={`intro ${introState === 1 ? "fold" : "unfold"}`}>
                  <div className="intro-content" ref={introContent}>
                    {novel.exhibitIntro}
                  </div>

                  {introState === 1 && (
                    <div className="view-all-btn" onClick={() => setIntroState(3)}>
                      ...查看全部
                    </div>
                  )}
                </div>
              ) : (
                <div className="no-intro-tip">暂无简介</div>
              )}
            </div>

            {/* 目录 */}
            {collectionList && !!collectionList.length && (
              <div className="novel-catalogue">
                <div className="title-container">
                  <span className="title">目录</span>
                  <span className="count">({total}章)</span>
                </div>

                <div className="sub-directory-container">
                  {collectionList.map((collectionItem: CollectionList) => {
                    return (
                      <div
                        className={`sub ${
                          (![0, 4].includes(collectionItem.defaulterIdentityType) ||
                            novel.onlineStatus === 0) &&
                          "disabled"
                        }`}
                        key={collectionItem.itemId}
                        onClick={() =>
                          history.switchPage(
                            `/reader?collection=${true}&id=${novel.exhibitId}&subId=${
                              collectionItem.itemId
                            }`
                          )
                        }
                      >
                        <span className="sub-title">{collectionItem.itemTitle}</span>
                        {collectionItem.articleInfo.status === 2 ? (
                          <img className="freeze-lock" src={Freeze} alt="封禁" />
                        ) : novel.onlineStatus === 0 ? (
                          <div className="offline-lock">已下架</div>
                        ) : ![0, 4].includes(collectionItem.defaulterIdentityType) ? (
                          <img className="auth-lock" src={AuthLinkAbnormal} alt="授权链异常" />
                        ) : collectionItem.defaulterIdentityType === 4 ? (
                          <img className="sub-lock" src={Lock} alt="未授权" />
                        ) : (
                          <img src={RightArrow} />
                        )}
                      </div>
                    );
                  })}
                </div>
                {collectionList.length === total && (
                  <div className="tip no-more">— 已加载全部章节 —</div>
                )}
              </div>
            )}
          </>
        )
      )}
    </div>
  ) : (
    // PC
    <div className={`content ${novel?.articleInfo.status === 2 && "freeze-exhibit"}`}>
      {novel?.articleInfo.status === 2 ? (
        <div className="freeze-exhibit">
          <div className="icon">
            <i className="freelog fl-icon-a-yichang_tupianshipinmanhuaziyuan freeze"> </i>
          </div>
          <span className="exceptional-text"> 此作品因违规无法访问 </span>
        </div>
      ) : (
        novel && (
          <div className="content-box">
            {/* 已下架、授权链异常 顶部提示窗 */}
            {(novel.onlineStatus === 0 || ![0, 4].includes(novel.defaulterIdentityType)) && (
              <div className="exceptional-message">
                {novel.onlineStatus === 0 ? "作品已下架，无法访问" : "作品异常，无法访问"}
              </div>
            )}

            {/* 授权链异常提示 */}
            {![0, 4].includes(novel.defaulterIdentityType) && (
              <div className="auth-link-abnormal-tip">
                <img className="auth-link-abnormal" src={AuthLinkAbnormal} alt="授权链异常" />
                <div className="tip-text">授权链异常，无法查看</div>
              </div>
            )}
            {/* 书籍信息 */}
            <div className="novel-info">
              <div className="novel-cover">
                <>
                  <img
                    className="novel-cover-image"
                    src={novel.coverImages[0]}
                    alt={novel.exhibitTitle}
                  />
                  {novel.onlineStatus === 0 && <div className="offline">已下架</div>}
                </>
              </div>

              <div className="novel-content">
                <div className="auth-link-abnormal-box">
                  {![0, 4].includes(novel.defaulterIdentityType) && (
                    <img className="auth-link-abnormal" src={AuthLinkAbnormal} alt="授权链异常" />
                  )}

                  <div className="novel-name">{novel.exhibitTitle}</div>
                </div>

                <div className="novel-author">{novel.articleInfo.articleOwnerName}</div>

                <div className="tags">
                  <Tags data={novel.tags || []} />
                </div>

                <div className="create-date">创建时间：{formatDate(novel.createDate)}</div>

                <div className="update-date">最近更新：{formatDate(novel.updateDate)}</div>

                <div className="btns-box">
                  <div className="operate-btns">
                    <div
                      className={`btn main-btn 
                    ${
                      (![0, 4].includes(novel.defaulterIdentityType) || novel.onlineStatus === 0) &&
                      "disabled"
                    }`}
                      onClick={async () => {
                        if (collectionList?.length) {
                          const res = await freelogApp.getUserData("novelLastViewedHistory");
                          const lastViewed = res?.data?.data || [];
                          const index = lastViewed.findIndex(
                            (i: { id: string }) => i.id === novel.exhibitId
                          );
                          const subId = lastViewed[index]?.subId;

                          history.switchPage(
                            `/reader?collection=${true}&id=${novel.exhibitId}&subId=${
                              subId || collectionList[0].itemId
                            }`
                          );
                        } else {
                          history.switchPage(`/reader?id=${novel.exhibitId}`);
                        }
                      }}
                    >
                      立即阅读
                    </div>
                    <div
                      className={`btn ${isCollected ? "warning-btn" : "collect-btn"}`}
                      onClick={() => operateShelf(novel)}
                    >
                      {isCollected ? "移出书架" : "加入书架"}
                    </div>
                  </div>

                  <div className="other-btns">
                    <div className="sign-count">{novel.signCount}人签约</div>
                    <div
                      className="share-btn"
                      onMouseOver={e => {
                        e.stopPropagation();
                        setShareWidgetShow(true);
                      }}
                      onMouseLeave={e => {
                        e.stopPropagation();
                        setShareWidgetShow(false);
                      }}
                    >
                      <span className="share-btn-text">
                        <i className="freelog fl-icon-fenxiang"></i>
                        分享给更多人
                      </span>

                      <div id="share" className="share-wrapper" />
                    </div>
                  </div>
                </div>
              </div>
            </div>
            {/* 书籍简介 */}
            <div className="novel-intro">
              <div className="intro-title">内容简介</div>

              {novel.exhibitIntro ? (
                <div className={`intro ${introState === 1 ? "fold" : "unfold"}`}>
                  <div className="intro-content" ref={introContent}>
                    {novel.exhibitIntro}
                  </div>

                  {introState === 1 && (
                    <div className="view-all-btn" onClick={() => setIntroState(3)}>
                      ...查看全部
                    </div>
                  )}
                </div>
              ) : (
                <div className="no-intro-tip">暂无简介</div>
              )}
            </div>
            {/* 目录 */}
            {collectionList && !!collectionList.length && (
              <div className="novel-catalogue">
                <div className="title-container">
                  <span className="title">目录</span>
                  <span className="count">({total}章)</span>
                  <div className="sort" onClick={handleSort}>
                    <span>{sortOrder === "asc" ? "正序" : "倒序"}</span>
                    <span className={`triangle ${sortOrder === "asc" ? "asc" : "desc"}`}></span>
                  </div>
                </div>

                <div className="sub-directory-container">
                  {collectionList.map((collectionItem: CollectionList) => {
                    return (
                      <div
                        className={`sub ${
                          (![0, 4].includes(collectionItem.defaulterIdentityType) ||
                            novel.onlineStatus === 0) &&
                          "disabled"
                        }`}
                        key={collectionItem.itemId}
                        onClick={() =>
                          history.switchPage(
                            `/reader?collection=${true}&id=${novel.exhibitId}&subId=${
                              collectionItem.itemId
                            }`
                          )
                        }
                      >
                        <span className="sub-title">{collectionItem.itemTitle}</span>
                        {collectionItem.articleInfo.status === 2 ? (
                          <img className="freeze-lock" src={Freeze} alt="封禁" />
                        ) : novel.onlineStatus === 0 ? (
                          <div className="offline-lock">已下架</div>
                        ) : ![0, 4].includes(collectionItem.defaulterIdentityType) ? (
                          <img className="auth-lock" src={AuthLinkAbnormal} alt="授权链异常" />
                        ) : collectionItem.defaulterIdentityType === 4 ? (
                          <img className="sub-lock" src={Lock} alt="未授权" />
                        ) : (
                          inMobile && <img src={RightArrow} />
                        )}
                      </div>
                    );
                  })}
                </div>
                {collectionList.length === total && (
                  <div className="tip no-more">— 已加载全部章节 —</div>
                )}
              </div>
            )}
          </div>
        )
      )}
    </div>
  );
};
