// comic-theme/src/views/reader.vue
<template>
  <div
    class="reader-wrapper"
    :class="{ 'in-mobile': inMobile, light: theme === 'light', dark: theme === 'dark' }"
    @click="clickPage()"
  >
    <my-header :readerHeader="true" v-if="(inMobile && mobileBarShow) || !inMobile" />

    <my-loader v-if="loading" />

    <!-- mobile -->
    <template v-if="!loading && inMobile">
      <div class="mobile-body-wrapper">
        <img class="content" :src="content" v-if="isAuth === true && content" />

        <div class="lock-box" v-if="isAuth === false">
          <img class="lock" src="../assets/images/lock.png" alt="未授权" />
          <div class="lock-tip">展品未开放授权，继续浏览请签约并获取授权</div>
          <div class="get-btn" @click="getAuth()">签约</div>
        </div>
      </div>

      <transition name="fade-down">
        <div class="mobile-operater-wrapper" @touchmove.prevent v-if="mobileBarShow">
          <!-- <div class="operater-btn">
            <i class="freelog fl-icon-zhankaigengduo"></i>
            <div class="operater-btn-label">上一话</div>
          </div>

          <div class="operater-btn" @click="directoryShow = true">
            <i class="freelog fl-icon-xiaoshuomulu"></i>
            <div class="operater-btn-label">目录</div>
          </div>

          <div class="operater-btn" @click="operateShelf(comicInfo)">
            <i
              class="freelog"
              :class="isCollected ? 'fl-icon-shoucangxiaoshuoyishoucang' : 'fl-icon-shoucangxiaoshuo'"
            ></i>
            <div class="operater-btn-label">{{ isCollected ? "取消收藏" : "加入收藏" }}</div>
          </div>

          <div class="operater-btn">
            <i class="freelog fl-icon-zhankaigengduo"></i>
            <div class="operater-btn-label">下一话</div>
          </div> -->

          <div class="single-btn" @click="operateShelf(comicInfo)">
            <i
              class="freelog"
              :class="isCollected ? 'fl-icon-shoucangxiaoshuoyishoucang' : 'fl-icon-shoucangxiaoshuo'"
            ></i>
            <div class="operater-btn-label">{{ isCollected ? "取消收藏" : "加入收藏" }}</div>
          </div>
        </div>
      </transition>
    </template>

    <!-- PC -->
    <template v-if="!loading && !inMobile">
      <div class="body-wrapper" :class="theme">
        <div class="breadcrumbs-wrapper">
          <div class="breadcrumbs-item">
            <div class="second-text-btn" @click="switchPage('/detail', { id: comicInfo.exhibitId })">
              {{ comicInfo.exhibitTitle }}
              <!-- {{comicInfo.exhibitTitle}} > -->
            </div>
          </div>

          <!-- <div class="breadcrumbs-item">
            <div class="current-page">
              {{ comicInfo.exhibitTitle }}
            </div>
          </div> -->
        </div>

        <div class="content-box">
          <img class="content" :src="content" v-if="isAuth === true && content" />

          <div class="lock-box" v-if="isAuth === false">
            <img class="lock" src="../assets/images/lock.png" alt="未授权" />
            <div class="lock-tip">展品未开放授权，继续浏览请签约并获取授权</div>
            <div class="get-btn" @click="getAuth()">签约</div>
          </div>
        </div>

        <div class="footer-bar">
          <div class="footer-btn invalid">上一话</div>
          <div class="footer-btn" @click="switchPage('/detail', { id: comicInfo.exhibitId })">
            漫画详情
          </div>
          <div class="footer-btn invalid">下一话</div>
        </div>
      </div>

      <div class="operater-wrapper">
        <div class="operater-btns-box">
          <!-- <operate-btn
            icon="fl-icon-xiaoshuomulu"
            :theme="theme"
            @click="
              clickPage();
              directoryShow = true;
            "
          /> -->

          <operate-btn
            :icon="isCollected ? 'fl-icon-shoucangxiaoshuoyishoucang' : 'fl-icon-shoucangxiaoshuo'"
            :theme="theme"
            @click="
              clickPage();
              operateShelf(comicInfo);
            "
          />

          <operate-btn icon="fl-icon-fenxiang" :theme="theme" @click.stop="sharePopupShow = true">
            <share :show="sharePopupShow" :exhibit="comicInfo" />
          </operate-btn>

          <operate-btn
            :icon="theme === 'light' ? 'fl-icon-rijianmoshi' : 'fl-icon-yejianmoshi'"
            :theme="theme"
            @click="
              clickPage();
              setTheme();
            "
          />

          <div class="back-top">
            <back-top>
              <operate-btn icon="fl-icon-huidaodingbu" :theme="theme" />
            </back-top>
          </div>
        </div>
      </div>
    </template>

    <directory :show="directoryShow" :comicInfo="comicInfo" @closeDirectory="directoryShow = false" />
  </div>
</template>

<script lang="tsx">
import { toRefs } from "@vue/reactivity";
import { useMyRouter, useMyScroll, useMyShelf } from "../utils/hooks";
import { defineAsyncComponent, reactive, watch, watchEffect } from "vue";
import { ExhibitItem } from "@/api/interface";
import { addAuth, getExhibitAuthStatus, getExhibitFileStream, getExhibitInfo } from "@/api/freelog";
import { useStore } from "vuex";

export default {
  name: "reader",

  components: {
    "my-header": defineAsyncComponent(() => import("../components/header.vue")),
    "operate-btn": defineAsyncComponent(() => import("../components/operate-btn.vue")),
    "my-loader": defineAsyncComponent(() => import("../components/loader.vue")),
    "back-top": defineAsyncComponent(() => import("../components/back-top.vue")),
    share: defineAsyncComponent(() => import("../components/share.vue")),
    directory: defineAsyncComponent(() => import("../components/directory.vue")),
  },

  setup() {
    const myTheme = localStorage.getItem("theme") || "light";
    const store = useStore();
    const { query, switchPage } = useMyRouter();
    const { id } = query.value;
    const { isCollected, operateShelf } = useMyShelf(id);
    const { scrollTop } = useMyScroll();

    const data = reactive({
      loading: false,
      comicInfo: {} as ExhibitItem,
      content: "",
      isAuth: null as boolean | null,
      theme: myTheme,
      sharePopupShow: false,
      directoryShow: false,
      mobileBarShow: true,
    });

    const methods = {
      // 点击页面
      clickPage() {
        if (data.sharePopupShow) data.sharePopupShow = false;
        if (store.state.inMobile && !data.mobileBarShow) data.mobileBarShow = true;
      },

      // 切换主题模式
      setTheme() {
        data.theme = data.theme === "light" ? "dark" : "light";
        localStorage.setItem("theme", data.theme);
      },

      async getAuth() {
        const authResult = await addAuth(id);
        const { status } = authResult;
        if (status === 0) {
          getContent();
          refreshAuth();
        }
      },
    };

    const getComicInfo = async () => {
      const exhibitInfo = await getExhibitInfo(id, { isLoadVersionProperty: 1 });
      data.comicInfo = exhibitInfo.data.data;
      getContent();
    };

    const getContent = async () => {
      data.loading = true;
      const statusInfo = await getExhibitAuthStatus(id);
      data.isAuth = statusInfo.data.data ? statusInfo.data.data[0].isAuth : false;
      if (data.isAuth) {
        const info: any = await getExhibitFileStream(id, true);
        if (!info) {
          data.loading = false;
          return;
        }

        data.content = info;
        data.loading = false;
      } else {
        data.loading = false;
        const authResult = await addAuth(id);
        const { status } = authResult;
        if (status === 0) {
          getContent();
          refreshAuth();
        }
      }
    };

    const refreshAuth = () => {
      const { authIds, myShelf } = store.state;
      authIds.push(id);
      store.commit("setData", { key: "authIds", value: authIds });
      const index = myShelf.findIndex((item: ExhibitItem) => item.exhibitId === id);
      if (index !== -1) {
        myShelf[index].isAuth = true;
        store.commit("setData", { key: "myShelf", value: myShelf });
      }
    };

    watchEffect(() => {
      document.body.style.overflowY = data.directoryShow && store.state.inMobile ? "hidden" : "auto";
    });

    watch(
      () => scrollTop.value,
      (cur) => {
        if (cur === 0 && !data.mobileBarShow) data.mobileBarShow = true;
        if (cur !== 0 && data.mobileBarShow) data.mobileBarShow = false;
      }
    );

    getComicInfo();

    return {
      ...toRefs(store.state),
      switchPage,
      isCollected,
      operateShelf,
      ...toRefs(data),
      ...methods,
    };
  },
};
</script>

<style lang="scss" scoped>
.reader-wrapper {
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;
  background-color: #fafbfc;
  transition: all 0.2s linear;

  &.in-mobile ::v-deep .mobile-header-wrapper {
    position: fixed;
    top: 0;
    z-index: 1;
  }

  &.dark {
    background-color: #333333;
  }

  &.light {
    background-color: #fafbfc;
  }

  // mobile 主题内容区
  .mobile-body-wrapper {
    width: 100%;
    flex: 1;
    padding-top: 60px;
    animation: fade-in 0.3s ease-out;
    transition: background-color 0.2s linear;

    &.dark {
      color: #999;
    }

    &.light {
      color: #222;
    }

    .content {
      width: 100%;
    }

    .lock-box {
      width: 100%;
      padding: 110px 0;
      display: flex;
      flex-direction: column;
      align-items: center;

      .lock {
        width: 48px;
        height: 48px;
      }

      .lock-tip {
        font-size: 16px;
        color: #999999;
        line-height: 22px;
        margin-top: 30px;
      }

      .get-btn {
        padding: 9px 20px;
        border-radius: 4px;
        font-size: 14px;
        line-height: 20px;
        font-weight: bold;
        background-color: #2784ff;
        color: #fff;
        margin-top: 30px;
        cursor: pointer;

        &:hover {
          background-color: #529dff;
        }

        &:active {
          background-color: #2376e5;
        }
      }
    }
  }

  // PC 主题内容区
  .body-wrapper {
    width: 800px;
    flex: 1;
    display: flex;
    flex-direction: column;

    .breadcrumbs-wrapper {
      display: flex;
      align-items: center;
      margin: 24px 0;
      font-size: 16px;
      font-weight: 600;
      line-height: 22px;

      .breadcrumbs-item {
        color: #999999;
      }

      .current-page {
        color: #222;
        margin-left: 10px;
      }
    }

    &.dark {
      .content-box {
        background-color: #373737;
      }

      .footer-bar {
        background-color: #373737;
        color: #999;

        .footer-btn.invalid {
          opacity: 0.4;
          pointer-events: none;
        }
      }
    }

    &.light {
      .content-box {
        background-color: #fff;
      }

      .footer-bar {
        background-color: #fff;
        color: #222;

        .footer-btn.invalid {
          opacity: 0.4;
          pointer-events: none;
        }
      }
    }

    .content-box {
      flex: 1;
      width: 100%;
      padding: 118px 60px;
      box-sizing: border-box;
      border-radius: 10px;
      animation: fade-in 0.3s ease-out;
      transition: all 0.2s linear;

      .content {
        width: 100%;
      }

      .lock-box {
        width: 100%;
        padding: 110px 0;
        display: flex;
        flex-direction: column;
        align-items: center;

        .lock {
          width: 48px;
          height: 48px;
        }

        .lock-tip {
          font-size: 16px;
          color: #999999;
          line-height: 22px;
          margin-top: 30px;
        }

        .get-btn {
          padding: 9px 20px;
          border-radius: 4px;
          font-size: 14px;
          line-height: 20px;
          font-weight: bold;
          background-color: #2784ff;
          color: #fff;
          margin-top: 30px;
          cursor: pointer;

          &:hover {
            background-color: #529dff;
          }

          &:active {
            background-color: #2376e5;
          }
        }
      }
    }

    .footer-bar {
      height: 78px;
      margin: 30px 0;
      border-radius: 10px;
      display: flex;
      align-items: center;
      transition: all 0.2s linear;

      .footer-btn {
        flex: 1;
        font-size: 16px;
        line-height: 30px;
        display: flex;
        align-items: center;
        justify-content: center;
        cursor: pointer;
        transition: all 0.2s linear;

        &:hover {
          color: #529dff;
        }

        &:active {
          color: #2376e5;
        }

        & + .footer-btn {
          border-left: 1px solid rgba(0, 0, 0, 0.2);
        }
      }
    }
  }

  // mobile 操作按钮群
  .mobile-operater-wrapper {
    position: fixed;
    left: 0;
    right: 0;
    bottom: 0;
    height: 60px;
    // padding: 0 20px;
    background-color: var(--deriveColor);
    display: flex;

    .single-btn {
      width: 100%;
      height: 100%;
      display: flex;
      align-items: center;
      justify-content: center;
      color: rgba(255, 255, 255, 0.6);

      &:active {
        color: #fff;
      }

      .freelog {
        width: 18px;
        height: 18px;
        font-size: 18px;
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .operater-btn-label {
        font-size: 14px;
        color: #ffffff;
        margin-left: 5px;
        margin-top: 2px;
      }
    }

    .operater-btn {
      flex: 1;
      display: flex;
      flex-direction: column;
      align-items: center;
      justify-content: center;
      color: rgba(255, 255, 255, 0.6);

      &:active {
        color: #fff;
      }

      &:first-child .freelog {
        transform: rotate(180deg);
      }

      .freelog {
        width: 18px;
        height: 18px;
        font-size: 18px;
        display: flex;
        align-items: center;
        justify-content: center;
      }

      .operater-btn-label {
        font-size: 10px;
        color: #ffffff;
        line-height: 16px;
        margin-top: 4px;
      }

      & + .operater-btn {
        margin-left: 10px;
      }
    }

    .hidden-input {
      position: absolute;
      left: -100%;
      z-index: -1;
    }
  }

  // PC 操作按钮群
  .operater-wrapper {
    position: fixed;
    bottom: 138px;
    left: 50%;
    margin-left: 500px;

    .operater-btns-box {
      position: absolute;
      right: 0;
      bottom: 0;
      display: flex;
      flex-direction: column;
      align-items: flex-end;

      .back-top {
        margin-top: 10px;
      }

      .share-wrapper {
        right: 100%;
        top: 50%;
        margin-top: -140px;
        margin-right: 20px;
      }
    }
  }
}

/* fade-up */
.fade-up-enter-active,
.fade-up-leave-active {
  transition: all 0.1s ease;
}
.fade-up-enter-from,
.fade-up-leave-to {
  opacity: 0;
  transform: translateY(-100%);
}

/* fade-down */
.fade-down-enter-active,
.fade-down-leave-active {
  transition: all 0.1s ease;
}
.fade-down-enter-from,
.fade-down-leave-to {
  opacity: 0;
  transform: translateY(100%);
}
</style>

// novel-theme/src/screens/reader/reader.tsx
import React, { useContext } from "react";
import "./reader.scss";
import Lock from "../../assets/images/lock.png";
import BgImage from "../../assets/images/reader-bg.png";
import { useState, useEffect, useCallback } from "react";
import { ExhibitItem, ThemeItem } from "../../api/interface";
import { addAuth, getExhibitAuthStatus, getExhibitFileStream, getExhibitInfo } from "../../api/freelog";
import { readerThemeList } from "../../api/data";
import { BackTop } from "../../components/back-top/back-top";
import { useMyHistory, useMyScroll, useMyShelf } from "../../utils/hooks";
import { Header } from "../../components/header/header";
import { Directory } from "../../components/directory/directory";
import { globalContext } from "../../router";
import { Share } from "../../components/share/share";
import { showToast } from "../../components/toast/toast";
import CSSTransition from "react-transition-group/CSSTransition";
import { Loader } from "../../components/loader/loader";

const readerContext = React.createContext<any>({});

export const ReaderScreen = (props: any) => {
  const id = props.match.params.id;
  const { inMobile } = useContext(globalContext);
  const myFontSize = Number(localStorage.getItem("fontSize"));
  const myTheme = JSON.parse(localStorage.getItem("theme") || "null");
  const [book, setBook] = useState<ExhibitItem | null>(null);
  const [fontSize, setFontSize] = useState(myFontSize || 22);
  const [theme, setTheme] = useState<ThemeItem>(myTheme || readerThemeList[0]);
  const [sharePopupShow, setSharePopupShow] = useState(false);
  const [fontSizePopupShow, setFontSizePopupShow] = useState(false);
  const [themePopupShow, setThemePopupShow] = useState(false);
  const [directoryShow, setDirectoryShow] = useState(false);
  const [mobileBarShow, setMobileBarShow] = useState(true);

  const context = {
    id,
    inMobile,
    book,
    setBook,
    fontSize,
    setFontSize,
    theme,
    setTheme,
    sharePopupShow,
    setSharePopupShow,
    fontSizePopupShow,
    setFontSizePopupShow,
    themePopupShow,
    setThemePopupShow,
    directoryShow,
    setDirectoryShow,
    mobileBarShow,
    setMobileBarShow,
  };

  const getBookInfo = useCallback(async () => {
    const exhibitInfo = await getExhibitInfo(id, { isLoadVersionProperty: 1 });
    setBook(exhibitInfo.data.data);
  }, [id]);

  const clickPage = () => {
    if (sharePopupShow || fontSizePopupShow || themePopupShow) {
      setSharePopupShow(false);
      setFontSizePopupShow(false);
      setThemePopupShow(false);
    }
    if (inMobile) setMobileBarShow(true);
  };

  useEffect(() => {
    getBookInfo();
    // eslint-disable-next-line
  }, [id]);

  return (
    <readerContext.Provider value={context}>
      <div
        className={`reader-wrapper ${inMobile && "in-mobile"}`}
        style={{ backgroundImage: `url(${BgImage})`, backgroundColor: theme?.bgColor }}
        onClick={() => clickPage()}
      >
        <CSSTransition in={(inMobile && mobileBarShow) || !inMobile} classNames="slide-up" timeout={150} unmountOnExit>
          <Header readerHeader={true} />
        </CSSTransition>

        <Body />

        <Operater />

        <Directory book={book} directoryShow={directoryShow} setDirectoryShow={setDirectoryShow} />
      </div>
    </readerContext.Provider>
  );
};

const Body = () => {
  const history = useMyHistory();
  const { inMobile, book, id, fontSize, theme } = useContext(readerContext);
  const [content, setContent] = useState<string[]>([]);
  const [isAuth, setIsAuth] = useState<boolean | null>(null);
  const [loading, setLoading] = useState(false);

  const getContent = useCallback(async () => {
    setLoading(true);
    const statusInfo = await getExhibitAuthStatus(id);
    const isAuth = statusInfo.data.data ? statusInfo.data.data[0].isAuth : false;
    setIsAuth(isAuth);
    if (isAuth) {
      const info: any = await getExhibitFileStream(id);
      if (!info) {
        setLoading(false);
        return;
      }
      const content = info.data.split(/\n/g).filter((item: string) => !!item);
      setContent(content);
      setLoading(false);
    } else {
      setLoading(false);
      const authResult = await addAuth(id);
      const { status } = authResult;
      if (status === 0) getContent();
    }
  }, [id]);

  const getAuth = async () => {
    const authResult = await addAuth(id);
    const { status } = authResult;
    if (status === 0) getContent();
  };

  useEffect(() => {
    getContent();
    // eslint-disable-next-line
  }, [id]);

  if (loading) {
    return <Loader />;
  } else if (inMobile === true) {
    // mobile
    return (
      <div
        className={`mobile-body-wrapper ${theme?.type === 1 ? "dark" : "light"}`}
        style={{
          backgroundImage: `url(${BgImage})`,
          backgroundColor: theme?.bookColor,
          fontSize: fontSize + "px",
          lineHeight: fontSize + 14 + "px",
        }}
      >
        {isAuth === true &&
          content.map((item, index) => {
            return (
              <p className="paragraph" key={item + index}>
                {item}
              </p>
            );
          })}
        {isAuth === false && (
          <div className="lock-box">
            <img className="lock" src={Lock} alt="未授权" />
            <div className="lock-tip">展品未开放授权，继续浏览请签约并获取授权</div>
            <div className="get-btn" onClick={() => getAuth()}>
              签约
            </div>
          </div>
        )}
      </div>
    );
  } else if (inMobile === false) {
    // PC
    return (
      <div className="body-wrapper">
        <div className="breadcrumbs-wrapper">
          <div className="breadcrumbs-item">
            <div className="second-text-btn" onClick={() => history.switchPage("/detail/" + id)}>
              {book?.exhibitTitle}
              {/* {book?.exhibitTitle} {">"} */}
            </div>
          </div>

          {/* <div className="breadcrumbs-item">
          <div className="current-page">
            {book?.exhibitTitle}
          </div>
        </div> */}
        </div>

        <div
          className={`content ${theme?.type === 1 ? "dark" : "light"}`}
          style={{
            backgroundImage: `url(${BgImage})`,
            backgroundColor: theme?.bookColor,
            fontSize: fontSize + "px",
            lineHeight: fontSize + 14 + "px",
          }}
        >
          {isAuth === true &&
            content.map((item, index) => {
              return (
                <p className="paragraph" key={item + index}>
                  {item}
                </p>
              );
            })}
          {isAuth === false && (
            <div className="lock-box">
              <img className="lock" src={Lock} alt="未授权" />
              <div className="lock-tip">展品未开放授权，继续浏览请签约并获取授权</div>
              <div className="get-btn" onClick={() => getAuth()}>
                签约
              </div>
            </div>
          )}
        </div>

        {/* <div
        className="footer-bar"
        style={{
          backgroundImage: `url(${BgImage})`,
          backgroundColor: theme?.bookColor,
          color: theme?.type === 1 ? "#999" : "#222",
        }}
      >
        <div className={`footer-btn invalid`} onClick={() => console.log(123)}>
          上一章
        </div>
        <div className="footer-btn" onClick={() => history.switchPage("/detail/" + id)}>
          书籍详情
        </div>
        <div className={`footer-btn invalid`} onClick={() => console.log(123)}>
          下一章
        </div>
      </div> */}
      </div>
    );
  } else {
    return <div></div>;
  }
};

const Operater = () => {
  const { scrollTop } = useMyScroll();
  const {
    inMobile,
    book,
    fontSize,
    setFontSize,
    theme,
    setTheme,
    sharePopupShow,
    setSharePopupShow,
    fontSizePopupShow,
    setFontSizePopupShow,
    themePopupShow,
    setThemePopupShow,
    mobileBarShow,
    setMobileBarShow,
  } = useContext(readerContext);
  const { isCollected, operateShelf } = useMyShelf(book?.exhibitId);
  const [href, setHref] = useState("");

  const changeFontSize = (type: number) => {
    let result = fontSize;
    if (type === 0) {
      if (result === 14) return;
      result--;
    } else {
      if (result === 36) return;
      result++;
    }
    setFontSize(result);
    localStorage.setItem("fontSize", result);
  };

  const closeAllPopup = () => {
    setSharePopupShow(false);
    setFontSizePopupShow(false);
    setThemePopupShow(false);
  };

  const share = () => {
    // 复制链接
    const input: any = document.getElementById("href");
    input.select();
    document.execCommand("Copy");
    showToast("链接复制成功～");
  };

  useEffect(() => {
    setHref((window.location as any).currentURL);
  }, []);

  useEffect(() => {
    if (sharePopupShow) setSharePopupShow(false);
    if (fontSizePopupShow) setFontSizePopupShow(false);
    if (themePopupShow) setThemePopupShow(false);
    if (scrollTop === 0 && !mobileBarShow) setMobileBarShow(true);
    if (scrollTop !== 0 && mobileBarShow) setMobileBarShow(false);
    // eslint-disable-next-line
  }, [scrollTop]);

  useEffect(() => {
    document.body.style.overflowY =
      (sharePopupShow || fontSizePopupShow || themePopupShow) && inMobile ? "hidden" : "auto";
  }, [sharePopupShow, fontSizePopupShow, themePopupShow, inMobile]);

  return inMobile ? (
    // mobile
    <CSSTransition in={mobileBarShow} classNames="slide-down" timeout={150} unmountOnExit>
      <div className="mobile-operater-wrapper">
        {/* <div
        className="operater-btn"
        onClick={() => {
          closeAllPopup();
          setDirectoryShow(true);
        }}
      >
        <i className="freelog fl-icon-xiaoshuomulu"></i>
        <div className="operater-btn-label">目录</div>
      </div> */}

        {isCollected ? (
          <div
            className="operater-btn"
            onClick={() => {
              closeAllPopup();
              operateShelf(book);
            }}
          >
            <i className="freelog fl-icon-shoucangxiaoshuoyishoucang"></i>
            <div className="operater-btn-label">移出书架</div>
          </div>
        ) : (
          <div
            className="operater-btn"
            onClick={() => {
              closeAllPopup();
              operateShelf(book);
            }}
          >
            <i className="freelog fl-icon-shoucangxiaoshuo"></i>
            <div className="operater-btn-label">加入书架</div>
          </div>
        )}

        <div
          className="operater-btn"
          onClick={() => {
            closeAllPopup();
            share();
          }}
        >
          <i className="freelog fl-icon-fenxiang"></i>
          <div className="operater-btn-label">分享</div>
        </div>

        <div
          className="operater-btn"
          onClick={() => {
            closeAllPopup();
            setFontSizePopupShow(true);
          }}
        >
          <div className="freelog">A</div>
          <div className="operater-btn-label">字号</div>
        </div>

        <div
          className="operater-btn"
          onClick={() => {
            closeAllPopup();
            setThemePopupShow(true);
          }}
        >
          <i className="freelog fl-icon-beijingyanse"></i>
          <div className="operater-btn-label">背景色</div>
        </div>

        {fontSizePopupShow && (
          <div className="operater-popup" onClick={() => setFontSizePopupShow(false)}>
            <div className="fontsize-popup" onClick={(e) => e.stopPropagation()}>
              <div className="fontsize-label" onClick={() => changeFontSize(0)}>
                A-
              </div>
              <div className="fontsize-value">{fontSize}</div>
              <div className="fontsize-label" onClick={() => changeFontSize(1)}>
                A+
              </div>
            </div>
          </div>
        )}

        {themePopupShow && (
          <div className="operater-popup" onClick={() => setThemePopupShow(false)}>
            <div className="theme-popup" onClick={(e) => e.stopPropagation()}>
              {readerThemeList.map((item) => {
                return (
                  <div
                    className={`theme-btn ${theme.bookColor === item.bookColor && "active"}`}
                    key={item.bookColor}
                    style={{ backgroundColor: item.bookColor }}
                    onClick={() => {
                      setTheme(item);
                      localStorage.setItem("theme", JSON.stringify(item));
                    }}
                  >
                    <i className="freelog fl-icon-xuanzhong"></i>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        <input id="href" className="hidden-input" value={href} readOnly />
      </div>
    </CSSTransition>
  ) : (
    // PC
    <div className="operater-wrapper">
      <div className="operater-btns-box">
        {/* <OperateBtn
          icon="fl-icon-xiaoshuomulu"
          onClick={() => {
            closeAllPopup();
            setDirectoryShow(true);
          }}
        /> */}

        {isCollected ? (
          <OperateBtn
            icon="fl-icon-shoucangxiaoshuoyishoucang"
            onClick={() => {
              closeAllPopup();
              operateShelf(book);
            }}
          />
        ) : (
          <OperateBtn
            icon="fl-icon-shoucangxiaoshuo"
            onClick={() => {
              closeAllPopup();
              operateShelf(book);
            }}
          />
        )}

        <OperateBtn
          icon="fl-icon-fenxiang"
          onClick={() => {
            closeAllPopup();
            setSharePopupShow(true);
          }}
          slot={<Share show={sharePopupShow} exhibit={book} />}
        />

        <OperateBtn
          text="A"
          onClick={() => {
            closeAllPopup();
            setFontSizePopupShow(true);
          }}
          slot={
            <div
              className={`operater-popup ${theme?.type === 1 ? "dark" : "light"}`}
              style={{ width: fontSizePopupShow ? "162px" : "0" }}
            >
              <div className="fontsize-label" onClick={() => changeFontSize(0)}>
                A-
              </div>
              <div className="fontsize-value">{fontSize}</div>
              <div className="fontsize-label" onClick={() => changeFontSize(1)}>
                A+
              </div>
            </div>
          }
        />

        <OperateBtn
          icon="fl-icon-beijingyanse"
          onClick={() => {
            closeAllPopup();
            setThemePopupShow(true);
          }}
          slot={
            <div className="operater-popup" style={{ width: themePopupShow ? "228px" : "0" }}>
              {readerThemeList.map((item) => {
                return (
                  <div
                    className={`theme-btn ${theme.bookColor === item.bookColor && "active"}`}
                    key={item.bookColor}
                    style={{ backgroundColor: item.bookColor }}
                    onClick={() => {
                      setTheme(item);
                      localStorage.setItem("theme", JSON.stringify(item));
                    }}
                  >
                    <i className="freelog fl-icon-xuanzhong"></i>
                  </div>
                );
              })}
            </div>
          }
        />

        <div className="back-top">
          <BackTop onClick={() => closeAllPopup()}>
            <OperateBtn icon="fl-icon-huidaodingbu" />
          </BackTop>
        </div>
      </div>
    </div>
  );
};

const OperateBtn = (props: { icon?: string; text?: string; slot?: any; onClick?: (e: any) => void }) => {
  const { icon, text, slot, onClick } = props;
  const { theme } = useContext(readerContext);

  return (
    <div
      className={`operate-btn-wrapper ${theme?.type === 1 ? "dark" : "light"}`}
      style={{ backgroundColor: theme?.bookColor }}
      onClick={(e) => e.stopPropagation()}
    >
      {slot}
      {icon && <i className={`freelog ${icon}`} onClick={onClick}></i>}
      {text && (
        <span className="freelog" onClick={onClick}>
          {text}
        </span>
      )}
    </div>
  );
};
