// 【8】mix-theme/src/components/back-top.vue
<!-- 回到顶部控件 -->

<template>
  <transition name="fade">
    <div @click="scrollToTop()" v-show="topBtnShow"><slot></slot></div>
  </transition>
</template>

<script lang="ts">
import { ref, watch } from "vue";
import { useMyScroll } from "../utils/hooks";

export default {
  name: "back-top",

  setup() {
    const { scrollTop, scrollToTop } = useMyScroll();
    const topBtnShow = ref(false);

    watch(
      () => scrollTop.value,
      cur => {
        topBtnShow.value = cur > 300;
      }
    );

    return {
      topBtnShow,
      scrollToTop
    };
  }
};
</script>

// 【1】novel-theme/src/components/back-top/back-top.tsx
import "./back-top.scss";
import CSSTransition from "react-transition-group/CSSTransition";
import { useMyScroll } from "../../utils/hooks";
import { TransitionChildren } from "react-transition-group/Transition";

/** 回到顶部控件 */
export const BackTop = (props: { children: TransitionChildren; onClick?: () => void }) => {
  const { scrollTop, scrollToTop } = useMyScroll();
  const { children, onClick } = props;

  /** 回到顶部 */
  const backToTop = () => {
    onClick && onClick();
    scrollToTop();
  };

  return (
    <CSSTransition
      in={scrollTop > 300}
      classNames="fade"
      timeout={500}
      unmountOnExit
      onClick={backToTop}
    >
      {children}
    </CSSTransition>
  );
};
