// novel-theme/src/components/tags/tags.tsx
import "./tags.scss";
import { useHistory } from "react-router-dom";

export const Tags = (props: { data: string[]; size: string }) => {
  const { data, size } = props;
  const history = useHistory();

  return (
    <div className="tags-wrapper w-100p flex-row flex-wrap">
      {data.map((tag) => (
        <div
          className={`tag brs-3 py-2 b-box text-center cur-pointer transition ${size}`}
          key={tag}
          title={`搜索${tag}漫画`}
          onClick={(e) => {
            e.stopPropagation();
            history.push(`/home/${tag}`);
          }}
        >
          {tag}
        </div>
      ))}
    </div>
  );
};

// comic-theme/src/components/tags.vue
<template>
  <div class="tags-wrapper w-100p flex-row flex-wrap">
    <div
      class="tag mb-10 brs-3 py-2 b-box text-center cur-pointer transition"
      :class="size"
      v-for="tag in data"
      :key="tag"
      :title="`搜索${tag}漫画`"
      @click="switchPage('/', { tag })"
    >
      {{ tag }}
    </div>
  </div>
</template>

<script lang="ts">
import { useMyRouter } from "@/utils/hooks";

export default {
  name: "tags",

  props: ["data", "size"],

  setup() {
    const { switchPage } = useMyRouter();
    return { switchPage };
  },
};
</script>

<style lang="scss" scoped>
.tag {
  &.large {
    font-size: 14px;
    padding: 0 10px;
    margin-right: 10px;
    margin-bottom: 10px;
    background-color: #9bcaff;
    color: #fff;

    &:hover {
      background-color: #7cb9ff;
    }
  }

  &.small {
    font-size: 12px;
    padding: 0 4px;
    margin-right: 5px;
    margin-bottom: 5px;
    border: 1px solid #ddd;
    color: #aaa;

    &:hover {
      background-color: #fff;
    }
  }
}
</style>
