// novel-theme/src/screens/home/home.tsx
import "./home.scss";
import { useState, useEffect, useCallback, useRef, useContext } from "react";
import { Header } from "../../components/header/header";
import { getExhibitAuthStatus, getExhibitListByPaging, GetExhibitListByPagingParams } from "../../api/freelog";
import { ExhibitItem } from "../../api/interface";
import { Novel } from "../../components/novel/novel";
import { useMyHistory, useMyScroll, useMyShelf } from "../../utils/hooks";
import { globalContext } from "../../router";
import { ThemeEntrance } from "../../components/theme-entrance/theme-entrance";
import { Footer } from "../../components/footer/footer";
import { LoginBtn } from "../../components/login-btn/login-btn";
import CSSTransition from "react-transition-group/CSSTransition";
import { Loader } from "../../components/loader/loader";

export const HomeScreen = (props: any) => {
  const { tags, keywords } = props.match.params;
  const { inMobile } = useContext(globalContext);
  const { scrollTop, clientHeight, scrollHeight } = useMyScroll();
  const [bookList, setBookList] = useState<ExhibitItem[]>([]);
  const [total, setTotal] = useState<number | null>(null);
  const [searching, setSearching] = useState(false);
  const [loading, setLoading] = useState(false);
  const [myloading, setMyloading] = useState(false);
  let skip = useRef(0);

  const getBookList = useCallback(
    async (init = false) => {
      if (myloading) return;

      setSearching(!!keywords);

      if (total === bookList.length && !init) return;

      if (init) setLoading(true);
      setMyloading(true);
      skip.current = init ? 0 : skip.current + 30;
      const queryParams: GetExhibitListByPagingParams = {
        articleResourceTypes: "文章",
        skip: skip.current,
        limit: 30,
      };
      if (tags !== "全部") queryParams.tags = tags;
      if (keywords) queryParams.keywords = keywords;

      const list = await getExhibitListByPaging(queryParams);
      const { dataList, totalItem } = list.data.data;
      if (dataList.length !== 0) {
        const ids = dataList.map((item: ExhibitItem) => item.exhibitId).join();
        const statusInfo = await getExhibitAuthStatus(ids);
        if (statusInfo.data.data) {
          dataList.forEach((item: ExhibitItem) => {
            const index = statusInfo.data.data.findIndex(
              (resultItem: { exhibitId: string }) => resultItem.exhibitId === item.exhibitId
            );
            if (index !== -1) item.defaulterIdentityType = statusInfo.data.data[index].defaulterIdentityType;
          });
        }
      }
      setBookList((pre) => (init ? dataList : [...pre, ...dataList]));
      setTotal(totalItem);
      if (init) setLoading(false);
      setMyloading(false);
    },
    // eslint-disable-next-line
    [bookList.length, total, tags, keywords]
  );

  useEffect(() => {
    getBookList(true);
    // eslint-disable-next-line
  }, [tags, keywords]);

  useEffect(() => {
    if (scrollTop + clientHeight === scrollHeight) getBookList();
    // eslint-disable-next-line
  }, [scrollTop, clientHeight, scrollHeight]);

  return (
    <div className="home-wrapper">
      <Header homeHeader={!searching} mobileSearching={(inMobile && searching) || false} defaultSearchKey={keywords} />

      <HomeBody
        bookList={bookList}
        searching={searching}
        total={total}
        tags={tags}
        keywords={keywords}
        loading={loading}
        myloading={myloading}
      />

      <Footer />

      <LoginBtn />

      <ThemeEntrance />
    </div>
  );
};

const HomeBody = (props: {
  bookList: ExhibitItem[];
  searching: boolean;
  total: number | null;
  tags: string;
  keywords: string;
  loading: boolean;
  myloading: boolean;
}) => {
  const { bookList, searching, total, tags, keywords, loading, myloading } = props;
  const { inMobile, userData, selfConfig } = useContext(globalContext);
  const tagsList: string[] = selfConfig.tags?.split(",");
  const { myShelf } = useMyShelf();
  const history = useMyHistory();
  const [filterBoxShow, setFilterBoxShow] = useState(false);

  const selectTag = (tag: string) => {
    let url = `/home/${tag}`;
    if (keywords) url += `/${keywords}`;
    history.switchPage(url);
  };

  if (inMobile === true) {
    // mobile
    return (
      <div className="mobile-home-body">
        {!searching && userData?.isLogin && myShelf && myShelf.length !== 0 && (
          <div className="shelf-book-list">
            <div className="shelf-header">
              <div className="box-title">我的书架</div>
              <div className="more-shelf" onClick={() => history.switchPage("/shelf")}>
                全部
                <i className="freelog fl-icon-zhankaigengduo"></i>
              </div>
            </div>

            <div className="book-list-box">
              {myShelf.map((item) => {
                return (
                  <div className="book-box" key={item.exhibitId}>
                    <Novel mode={4} data={item}></Novel>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        <div className="book-list">
          {searching ? (
            <div className="search-box-title">
              <div className="box-title">查询到{bookList.length}个相关结果</div>
              <div className={`text-btn mobile ${myloading && "disabled"}`} onClick={() => setFilterBoxShow(true)}>
                <i className="freelog fl-icon-shaixuan"></i>
                <div className="filter-label">筛选</div>
              </div>
            </div>
          ) : (
            <div className="box-header">
              <div className="box-title">精选小说</div>
              <div className={`text-btn mobile ${myloading && "disabled"}`} onClick={() => setFilterBoxShow(true)}>
                <i className="freelog fl-icon-shaixuan"></i>
                <div className="filter-label">筛选</div>
              </div>
            </div>
          )}

          {loading && <Loader />}

          {!loading &&
            bookList.map((item) => {
              return (
                <div key={item.exhibitId} className="book-box">
                  <Novel data={item}></Novel>
                </div>
              );
            })}

          {!loading && bookList.length === 0 && <div className="tip">当前节点暂无任何书籍，请稍后查看</div>}

          {!loading && bookList.length !== 0 && bookList.length === total && (
            <div className="tip no-more">— 已加载全部书籍 —</div>
          )}
        </div>

        <CSSTransition in={filterBoxShow} classNames="fade" timeout={200} unmountOnExit>
          <div id="modal" className="modal" onClick={() => setFilterBoxShow(false)}></div>
        </CSSTransition>
        <CSSTransition in={filterBoxShow} classNames="slide-right" timeout={200} unmountOnExit>
          <div className="filter-box-body">
            <div className="filter-box-header">
              <div className="header-title">按标签筛选</div>
              <div className="close-btn" onClick={() => setFilterBoxShow(false)}>
                <i className="freelog fl-icon-guanbi"></i>
              </div>
            </div>
            <div className="tags-box">
              <div
                className={`tag ${tags === "全部" && "active"}`}
                onClick={() => {
                  setFilterBoxShow(false);
                  selectTag("全部");
                }}
              >
                全部
              </div>
              <div className="tags-box-list">
                {tagsList.map((item) => (
                  <div
                    className={`tag ${tags === item && "active"}`}
                    key={item}
                    onClick={() => {
                      setFilterBoxShow(false);
                      selectTag(item);
                    }}
                  >
                    {item}
                  </div>
                ))}
              </div>
            </div>
          </div>
        </CSSTransition>
      </div>
    );
  } else if (inMobile === false) {
    // PC
    return (
      <div className="home-body">
        {!searching && userData?.isLogin && myShelf && myShelf.length !== 0 && (
          <div className="book-list">
            <div className="shelf-header">
              <div className="box-title">我的书架</div>
              <div className="shelf-header-right">
                <div className="text-btn" onClick={() => history.switchPage("/shelf")}>
                  管理书架
                </div>
              </div>
            </div>

            <div className="book-list-box">
              {myShelf.map((item) => {
                return (
                  <div className="book-box" key={item.exhibitId}>
                    <Novel data={item}></Novel>
                  </div>
                );
              })}
            </div>
          </div>
        )}

        <div className="book-list">
          {searching ? (
            <div className="search-box-title">查询到{bookList.length}个相关结果</div>
          ) : (
            <div className="box-title">精选小说</div>
          )}
          <div className="filter-bar">
            <div className="filter-bar-bg"></div>

            <div
              className={`category-btn ${tags === "全部" && "active"} ${myloading && "disabled"}`}
              onClick={() => selectTag("全部")}
            >
              全部
            </div>

            {tagsList.map((item) => {
              return (
                <div
                  className={`category-btn ${tags === item && "active"} ${myloading && "disabled"}`}
                  key={item}
                  onClick={() => selectTag(item)}
                >
                  {item}
                </div>
              );
            })}
          </div>

          {loading && <Loader />}

          {!loading && (
            <div className="book-list-box">
              {bookList.map((item) => {
                return (
                  <div key={item.exhibitId} className="book-box">
                    <Novel data={item}></Novel>
                  </div>
                );
              })}
            </div>
          )}
          {!loading && bookList.length === 0 && <div className="tip">当前节点暂无任何书籍，请稍后查看</div>}
          {!loading && bookList.length !== 0 && bookList.length === total && (
            <div className="tip no-more">— 已加载全部书籍 —</div>
          )}
        </div>
      </div>
    );
  } else {
    return <div></div>;
  }
};

// blog-theme/src/views/home.vue
<template>
  <div class="home-wrapper" @click="sortPopupShow = false">
    <my-header homeHeader :mobileSearching="!!(inMobile && searchData.keywords)" />

    <!-- mobile -->
    <div class="mobile-home-body" v-if="inMobile">
      <div class="header">
        <div class="sort" v-if="!searchData.keywords" @click.stop="sortPopupShow = true">
          {{ createDateSortType === "-1" ? "最新" : "最早" }}
          <i class="freelog fl-icon-zhankaigengduo"></i>

          <transition name="slide-down-scale">
            <div class="sort-popup" @click.stop v-show="sortPopupShow">
              <div class="sort-popup-body">
                <div
                  class="user-box-btn"
                  @click="
                    sort('-1');
                    sortPopupShow = false;
                  "
                >
                  最新
                </div>
                <div
                  class="user-box-btn"
                  @click="
                    sort('1');
                    sortPopupShow = false;
                  "
                >
                  最早
                </div>
              </div>
            </div>
          </transition>
        </div>

        <div class="box-title" v-if="searchData.keywords">查询到{{ listData.length }}个相关结果</div>

        <div class="text-btn mobile" @click="filterBoxShow = true">
          <i className="freelog fl-icon-shaixuan"></i>
          <div class="filter-label">筛选</div>
        </div>
      </div>

      <my-loader v-if="loading" />

      <template v-if="!loading">
        <div class="article-list">
          <my-article :data="item" v-for="item in listData" :key="item.presentableId" />
        </div>

        <div className="tip" v-show="total === 0">当前节点暂无任何书籍，请稍后查看</div>
        <div className="tip no-more" v-show="listData.length !== 0 && listData.length === total">
          — 已加载全部书籍 —
        </div>
      </template>

      <transition name="fade">
        <div id="modal" class="modal" v-if="filterBoxShow" @click="filterBoxShow = false"></div>
      </transition>
      <transition name="slide-right">
        <div class="filter-box-body" v-if="filterBoxShow">
          <div class="filter-box-header">
            <div class="header-title">按标签筛选</div>
            <div class="close-btn" @click="filterBoxShow = false">
              <i class="freelog fl-icon-guanbi"></i>
            </div>
          </div>
          <div class="tags-box">
            <div
              class="tag"
              :class="{ active: !searchData.tags }"
              @click="
                filterBoxShow = false;
                selectTag();
              "
            >
              全部
            </div>
            <div class="tags-box-list">
              <div
                class="tag"
                :class="{ active: searchData.tags === item }"
                v-for="item in tagsList"
                :key="item"
                @click="
                  filterBoxShow = false;
                  selectTag(item);
                "
              >
                {{ item }}
              </div>
            </div>
          </div>
        </div>
      </transition>
    </div>

    <!-- PC -->
    <div class="home-body" v-if="!inMobile">
      <div class="header">
        <div class="search-box-title" v-if="searchData.keywords">查询到{{ listData.length }}个相关结果</div>

        <div class="filter-bar">
          <div class="filter-bar-bg"></div>

          <div class="category-btn" :class="{ active: !searchData.tags }" @click="selectTag()">全部</div>

          <div
            class="category-btn"
            :class="{ active: searchData.tags === item }"
            v-for="item in tagsList"
            :key="item"
            @click="selectTag(item)"
          >
            {{ item }}
          </div>
        </div>

        <div
          class="sort"
          @mouseover="sortPopupShow = true"
          @mouseleave="sortPopupShow = false"
          v-if="!searchData.keywords && !searchData.tags"
        >
          {{ createDateSortType === "-1" ? "最新" : "最早" }}
          <i class="freelog fl-icon-zhankaigengduo"></i>

          <transition name="slide-down-scale">
            <div class="sort-popup" v-show="sortPopupShow">
              <div class="sort-popup-body">
                <div class="user-box-btn" @click="sort('-1')">最新</div>
                <div class="user-box-btn" @click="sort('1')">最早</div>
              </div>
            </div>
          </transition>
        </div>
      </div>

      <my-loader v-if="loading" />

      <template v-if="!loading">
        <div class="article-list">
          <my-article :data="item" v-for="item in listData" :key="item.presentableId" />
        </div>

        <div className="tip" v-show="total === 0">当前节点暂无任何书籍，请稍后查看</div>
        <div className="tip no-more" v-show="listData.length !== 0 && listData.length === total">
          — 已加载全部书籍 —
        </div>
      </template>
    </div>

    <my-footer />
  </div>
</template>

<script lang="ts">
import { defineAsyncComponent, onActivated, onDeactivated, reactive, toRefs, watch } from "vue";
import { useGetList, useMyRouter, useMyScroll } from "../utils/hooks";
import { useStore } from "vuex";

export default {
  name: "home",

  components: {
    "my-header": defineAsyncComponent(() => import("../components/header.vue")),
    "my-loader": defineAsyncComponent(() => import("../components/loader.vue")),
    "my-footer": defineAsyncComponent(() => import("../components/footer.vue")),
    "my-article": defineAsyncComponent(() => import("../components/article.vue")),
  },

  setup() {
    const store = useStore();
    const tagsList: string[] = store.state.selfConfig.tags.split(",");
    const { query, route, router, switchPage } = useMyRouter();
    const { scrollTop, clientHeight, scrollHeight, scrollTo } = useMyScroll();
    const datasOfGetList = useGetList();

    const data = reactive({
      sortPopupShow: false,
      createDateSortType: "-1",
      searchData: {} as { keywords?: string; tags?: string; sort?: string },
      filterBoxShow: false,
    });

    const methods = {
      // 排序
      sort(sortType: string) {
        if (data.createDateSortType === sortType) return;

        data.createDateSortType = sortType;
        data.searchData.sort = `createDate:${sortType}`;
        datasOfGetList.getList(data.searchData, true);
      },

      // 清除搜索
      clearSearch() {
        data.searchData = {};
        switchPage("/home");
      },

      // 筛选标签
      selectTag(tag: string) {
        const { keywords } = data.searchData;
        const query: { keywords?: string; tags?: string } = {};
        if (tag) query.tags = tag;
        if (keywords) query.keywords = keywords;
        switchPage("/home", query);
      },
    };

    watch(
      () => scrollTop.value,
      (cur) => {
        if (cur + clientHeight.value === scrollHeight.value) {
          datasOfGetList.getList();
        }
      }
    );

    watch(
      () => query.value,
      () => {
        if (route.path !== "/home") return;
        if (
          data.searchData.keywords === query.value.keywords &&
          data.searchData.tags === query.value.tags &&
          data.searchData.sort === query.value.sort
        )
          return;

        getData();
      }
    );

    // 获取数据
    const getData = () => {
      data.searchData = query.value;
      datasOfGetList.clearData();
      datasOfGetList.getList(data.searchData, true);
    };

    onActivated(() => {
      if (router.options.history.state.replaced) {
        const homeScrollTop = sessionStorage.getItem("homeScroll");
        scrollTo(Number(homeScrollTop), "auto");

        const { authIds } = store.state;
        if (authIds.length === 0) return;

        authIds.forEach((id: string) => {
          const index = datasOfGetList.listData.value.findIndex((item) => item.exhibitId === id);
          if (index !== -1) datasOfGetList.listData.value[index].defaulterIdentityType = 0;
        });
        store.commit("setData", { key: "authIds", value: [] });
      } else {
        getData();
      }
    });

    onDeactivated(() => {
      sessionStorage.setItem("homeScroll", String(scrollTop.value));
    });

    getData();

    return {
      ...toRefs(store.state),
      tagsList,
      ...datasOfGetList,
      ...toRefs(data),
      ...methods,
    };
  },
};
</script>

<style lang="scss" scoped>
.home-wrapper {
  position: relative;
  width: 100%;
  min-height: 100vh;
  display: flex;
  flex-direction: column;
  align-items: center;

  // mobile
  .mobile-home-body {
    width: 100%;
    padding: 0 20px;
    box-sizing: border-box;
    padding-bottom: 98px;

    .header {
      width: 100%;
      display: flex;
      align-items: center;
      justify-content: space-between;
      padding: 30px 0;
      border-bottom: 1px solid rgba(0, 0, 0, 0.08);

      .sort {
        position: relative;
        font-size: 16px;
        line-height: 22px;
        display: flex;
        align-items: center;

        .freelog {
          font-size: 12px;
          width: 12px;
          height: 7px;
          display: flex;
          align-items: center;
          justify-content: center;
          margin-left: 5px;
          transform: rotate(90deg);
        }

        .sort-popup {
          position: absolute;
          left: 0;
          top: 100%;
          padding-top: 5px;
          z-index: 1;

          .sort-popup-body {
            width: 118px;
            background: #ffffff;
            box-shadow: 0px 2px 5px 0px rgba(0, 0, 0, 0.2);
            padding: 10px 0;

            .user-box-btn {
              width: 100%;
              height: 40px;
              padding: 0 20px;
              box-sizing: border-box;
              font-size: 14px;
              line-height: 40px;
              cursor: pointer;
            }
          }
        }
      }

      .box-title {
        font-size: 16px;
        color: #999999;
        line-height: 22px;
      }

      .text-btn {
        display: flex;
        align-items: center;

        .freelog {
          font-size: 18px;
        }

        .filter-label {
          font-size: 16px;
          line-height: 22px;
          margin-left: 5px;
        }
      }
    }

    .tip {
      width: 100%;
      text-align: center;
      font-size: 16px;
      line-height: 22px;
      color: #999;
      margin-top: 55px;

      &.no-more {
        font-size: 14px;
        line-height: 20px;
        margin: 30px 0;
      }
    }

    .modal {
      position: fixed;
      left: 0;
      top: 0;
      right: 0;
      bottom: 0;
      background-color: rgba(0, 0, 0, 0.4);
      z-index: 101;
    }

    .filter-box-body {
      position: fixed;
      left: 0;
      top: 0;
      bottom: 0;
      width: 340px;
      background: #ffffff;
      border-radius: 0px 10px 10px 0px;
      padding: 0 20px;
      box-sizing: border-box;
      overflow: hidden;
      display: flex;
      flex-direction: column;
      z-index: 101;

      .filter-box-header {
        position: relative;
        width: 100%;
        display: flex;
        align-items: center;
        justify-content: space-between;
        margin-top: 26px;

        .header-title {
          font-size: 16px;
          font-weight: 600;
          color: #222222;
          line-height: 22px;
        }

        .close-btn {
          width: 22px;
          height: 22px;
          display: flex;
          align-items: center;
          justify-content: center;
          margin-right: 6px;

          .freelog {
            font-size: 12px;
            color: #333;
            display: flex;
            align-items: center;
            justify-content: center;
          }
        }
      }

      .tags-box {
        width: 100%;
        flex: 1;
        display: flex;
        flex-direction: column;
        margin-top: 30px;
        padding-left: 12px;
        box-sizing: border-box;

        .tags-box-list {
          width: 100%;
          display: flex;
          flex-wrap: wrap;
          margin-top: 15px;
        }

        .tag {
          width: fit-content;
          height: 38px;
          border-radius: 38px;
          padding: 9px 15px;
          box-sizing: border-box;
          background: #ebecf0;
          font-size: 14px;
          color: #575e6a;
          line-height: 20px;
          margin: 0 5px 15px;
          cursor: pointer;

          &.active {
            background: var(--deriveColor);
            color: #fff;
          }
        }
      }
    }
  }

  // PC
  .home-body {
    width: 920px;
    padding-bottom: 148px;

    .header {
      font-size: 30px;
      line-height: 36px;
      margin-bottom: 30px;

      .search-box-title {
        font-size: 14px;
        color: #999999;
        line-height: 20px;
        margin-top: 30px;
      }

      .filter-bar {
        position: relative;
        width: 100%;
        height: 50px;
        border-radius: 6px;
        display: flex;
        align-items: center;
        justify-content: center;
        overflow: hidden;
        margin: 30px 0;

        .filter-bar-bg {
          position: absolute;
          inset: 0;
          background-color: var(--deriveColor);
          opacity: 0.04;
        }

        .category-btn {
          position: relative;
          height: 24px;
          padding: 2px 8px;
          box-sizing: border-box;
          font-size: 14px;
          color: #666;
          line-height: 20px;
          border-radius: 12px;
          cursor: pointer;
          transition: all 0.2s linear;
          z-index: 1;

          &:hover {
            color: var(--deriveColor);
          }

          &:active {
            color: var(--deriveColor);
            opacity: 0.8;
          }

          &.active {
            background-color: var(--deriveColor);
            color: #fff;
          }

          & + .category-btn {
            margin-left: 4px;
          }
        }
      }

      .sort {
        position: relative;
        width: fit-content;
        display: flex;
        align-items: center;
        font-size: 14px;
        font-weight: 600;
        color: #222222;
        line-height: 20px;
        cursor: pointer;

        .freelog {
          font-size: 12px;
          width: 12px;
          height: 7px;
          display: flex;
          align-items: center;
          justify-content: center;
          margin-left: 5px;
          transform: rotate(90deg);
        }

        .sort-popup {
          position: absolute;
          left: 0;
          top: 100%;
          padding-top: 5px;
          z-index: 1;

          .sort-popup-body {
            width: 118px;
            background: #ffffff;
            box-shadow: 0px 2px 5px 0px rgba(0, 0, 0, 0.2);
            padding: 10px 0;

            .user-box-btn {
              width: 100%;
              height: 40px;
              padding: 0 20px;
              box-sizing: border-box;
              font-size: 14px;
              line-height: 40px;
              cursor: pointer;
            }
          }
        }
      }
    }

    .article-list .article-wrapper:first-child {
      border-top: 1px solid rgba(0, 0, 0, 0.1);
    }

    .tip {
      width: 100%;
      text-align: center;
      font-size: 16px;
      line-height: 22px;
      color: #999;
      margin-top: 55px;

      &.no-more {
        font-size: 14px;
        line-height: 20px;
        margin-top: 30px;
      }
    }
  }
}
</style>
