// blog-theme/src/components/login-btn.vue
<template>
  <div
    class="login-btn-wrapper main-btn mobile"
    :class="{ hidden: userData || !inMobile }"
    :style="{ boxShadow: `0px 2px 10px 0px ${theme.deriveColor}40` }"
    @click="callLogin()"
  >
    登录 / 注册
  </div>
</template>

<script lang="ts">
import { useStore } from "vuex";
import { callLogin } from "@/api/freelog";

export default {
  name: "login-btn",

  setup() {
    const store = useStore();

    return {
      ...store.state,
      callLogin,
    };
  },
};
</script>

<style lang="scss" scoped>
.login-btn-wrapper {
  position: fixed;
  bottom: 50px;
  left: 50%;
  transform: translateX(-50%);
  width: 240px;
  height: 60px;
  border-radius: 60px;
  font-size: 16px;
  font-weight: 600;
  color: #ffffff;
  box-shadow: 0px 2px 10px 0px rgba(39, 132, 255, 0.4);
  display: flex;
  align-items: center;
  justify-content: center;
  z-index: 100;

  &.hidden {
    display: none;
  }
}
</style>

// novel-theme/src/components/login-btn/login-btn.tsx
import { useContext } from "react";
import { callLogin } from "../../api/freelog";
import { globalContext } from "../../router";
import "./login-btn.scss";

export const LoginBtn = () => {
  const { userData, inMobile, theme } = useContext(globalContext);

  return (
    <div
      className={`login-btn-wrapper main-btn mobile ${(userData || !inMobile) && "hidden"}`}
      style={{ boxShadow: `0px 2px 10px 0px ${theme.deriveColor}40` }}
      onClick={() => callLogin()}
    >
      登录 / 注册
    </div>
  );
};
