// document-theme/src/components/share.vue
<template>
  <transition name="fade">
    <div class="share-wrapper" @click.stop v-if="show">
      <div class="share-popup">
        <div class="share-title">分享</div>

        <input id="href" class="hidden-input" :value="href" readOnly />

        <textarea class="textarea" v-model="shareText"></textarea>

        <div class="btns-box">
          <div class="share-btns">
            <div class="share-label">快速分享至：</div>
            <div
              class="share-btn-item"
              :style="{ backgroundColor: item.bgColor }"
              v-for="item in shareBtns"
              :key="item.id"
              @click="share(item)"
            >
              <i class="freelog" :class="item.icon"></i>
            </div>
          </div>

          <div class="copy-btn" @click="share({ id: 'copy', name: '' })">复制链接</div>

          <transition name="fade">
            <div class="qrcode-popup-wrapper" @click="qrcodeShow = false" v-if="qrcodeShow">
              <div class="qrcode-popup" @click.stop>
                <i class="close-btn freelog fl-icon-guanbi" @click="qrcodeShow = false"></i>
                <div class="qrcode-text">分享到{{ qrcodeInfo.name }}</div>
                <qrcode-vue :value="qrcodeInfo.url" :size="220" level="M" />
                <div class="qrcode-text">使用{{ qrcodeInfo.name }}扫一扫完成分享</div>
              </div>
            </div>
          </transition>
        </div>
      </div>
    </div>
  </transition>
</template>

<script lang="ts">
import { useStore } from "vuex";
import { reactive, toRefs } from "@vue/reactivity";
import { ExhibitItem } from "@/api/interface";
import { shareBtns } from "@/api/data";
import { showToast } from "@/utils/common";
import { watch } from "vue";
import QrcodeVue from "qrcode.vue";

export default {
  name: "share",

  components: {
    QrcodeVue
  },

  props: ["show", "exhibit"],

  setup(props: { show: boolean; exhibit: ExhibitItem }) {
    const store = useStore();

    const data = reactive({
      shareText: "",
      href: "",
      qrcodeShow: false,
      qrcodeInfo: { name: "", url: "" },
    });

    const methods = {
      share(item: { id: string; name: string }) {
        const url = data.href;
        const title = props.exhibit?.exhibitTitle;
        const summary = ``;
        const image = props.exhibit?.coverImages[0];

        if (item.id === "qqZone") {
          // QQ空间
          const shareWeb = `https://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=${url}&desc=${data.shareText}&summary=${summary}&title=${title}&pics=${image}`;
          window.open(shareWeb);
        } else if (item.id === "weibo") {
          // 微博
          const weiboTitle = `我在freelog发现一个不错的文档：${props.exhibit?.exhibitTitle}`;
          window.open(`https://service.weibo.com/share/share.php?url=${url}&title=${weiboTitle}&pic=${image}`);
        } else if (item.id === "douban") {
          // 豆瓣
          window.open(`https://www.douban.com/share/service?url=${url}&title=${title}&image=${image}`);
        } else if (["qq", "wechat"].includes(item.id)) {
          // qq、微信
          data.qrcodeInfo = { name: item.name, url };
          data.qrcodeShow = true;
        } else if (item.id === "copy") {
          // 复制链接
          const input: any = document.getElementById("href");
          input.select();
          document.execCommand("Copy");
          showToast("链接复制成功～");
        }
      },
    };

    const initShare = () => {
      const url = (window.location as any).currentURL;
      data.href = url;
      data.shareText = `我在freelog发现一个不错的文档：${props.exhibit?.exhibitTitle} ${url}`;
      if (!props.show) data.qrcodeShow = false;
    };

    watch(
      () => props.exhibit,
      () => {
        initShare();
      }
    );

    return {
      shareBtns,
      ...store.state,
      ...toRefs(data),
      ...methods,
    };
  },
};
</script>

<style lang="scss" scoped>
.share-wrapper {
  position: absolute;
  right: 0;
  bottom: 120%;
  z-index: 1;
  cursor: default;

  .share-popup {
    width: 650px;
    padding: 17px 30px 20px;
    box-sizing: border-box;
    background-color: #ffffff;
    box-shadow: 0px 2px 5px 0px rgba(0, 0, 0, 0.4);
    border-radius: 6px;

    .share-title {
      font-size: 14px;
      font-weight: 600;
      color: #222222;
      line-height: 20px;
    }

    .hidden-input {
      position: absolute;
      z-index: -1;
    }

    .textarea {
      width: 100%;
      height: 100px;
      border-radius: 4px;
      border: 1px solid #d8d8d8;
      padding: 10px;
      box-sizing: border-box;
      font-size: 14px;
      color: #222222;
      line-height: 20px;
      margin-top: 17px;
      outline: none;
      resize: none;
    }

    .btns-box {
      display: flex;
      justify-content: space-between;
      margin-top: 12px;

      .share-btns {
        position: relative;
        display: flex;
        align-items: center;

        .share-label {
          font-size: 12px;
          color: #999999;
          margin-right: 10px;
        }

        .share-btn-item {
          width: 38px;
          height: 38px;
          border-radius: 4px;
          display: flex;
          align-items: center;
          justify-content: center;
          cursor: pointer;

          .freelog {
            font-size: 20px;
            color: #fff;
          }

          & + .share-btn-item {
            margin-left: 15px;
          }
        }

        .qq-iframe {
          position: absolute;
          height: 500px;
          left: 0px;
          bottom: 100%;
        }
      }

      .copy-btn {
        padding: 0 20px;
        height: 38px;
        border-radius: 4px;
        font-size: 14px;
        color: #fff;
        background-color: #2784ff;
        display: flex;
        align-items: center;
        justify-content: center;
        cursor: pointer;
        font-weight: bold;

        &:hover {
          background-color: #529dff;
        }

        &:active {
          background-color: #2376e5;
        }
      }

      .qrcode-popup-wrapper {
        position: fixed;
        inset: 0;
        display: flex;
        align-items: center;
        justify-content: center;
        background-color: rgba(0, 0, 0, 0.3);

        .qrcode-popup {
          position: relative;
          padding: 0 30px;
          background-color: #ffffff;
          border-radius: 6px;
          border: 1px solid #dddddd;
          display: flex;
          flex-direction: column;
          align-items: center;

          .qrcode-text {
            font-size: 16px;
            color: #222222;
            line-height: 22px;
            margin: 20px 0;
          }

          .close-btn {
            position: absolute;
            top: 22px;
            right: 30px;
            width: 12px;
            height: 22px;
            font-size: 12px;
            color: #333;
            cursor: pointer;
          }
        }
      }
    }
  }
}
</style>

// novel-theme/src/components/share/share.tsx
import "./share.scss";
import CSSTransition from "react-transition-group/CSSTransition";
import { useContext, useEffect, useState } from "react";
import { ExhibitItem, shareBtnItem } from "../../api/interface";
import { shareBtns } from "../../api/data";
import { showToast } from "../toast/toast";
import { globalContext } from "../../router";
const QRCode = require("qrcode.react");

export const Share = (props: {
  show: boolean;
  setShareShow?: (show: boolean) => void;
  exhibit: ExhibitItem | null;
}) => {
  const { inMobile } = useContext(globalContext);
  const { show, setShareShow, exhibit } = props;
  const [shareText, setShareText] = useState("");
  const [href, setHref] = useState("");
  const [qrcodeShow, setQrcodeShow] = useState(false);
  const [qrcodeInfo, setQrcodeInfo] = useState<{ name: string; url: string }>({
    name: "",
    url: "",
  });

  const share = (item: { id: string; name: string }) => {
    const url = href;
    const title = exhibit?.exhibitTitle;
    const summary = ``;
    const image = exhibit?.coverImages[0];

    if (item.id === "qqZone") {
      // QQ空间
      const shareWeb = `https://sns.qzone.qq.com/cgi-bin/qzshare/cgi_qzshare_onekey?url=${url}&desc=${shareText}&summary=${summary}&title=${title}&pics=${image}`;
      window.open(shareWeb);
    } else if (item.id === "weibo") {
      // 微博
      const weiboTitle = `我在freelog发现一个不错的小说：${exhibit?.exhibitTitle}`;
      window.open(`https://service.weibo.com/share/share.php?url=${url}&title=${weiboTitle}&pic=${image}`);
    } else if (item.id === "douban") {
      // 豆瓣
      window.open(`https://www.douban.com/share/service?url=${url}&title=${title}&image=${image}`);
    } else if (["qq", "wechat"].includes(item.id)) {
      // qq、微信
      const qrcodeInfo = { name: item.name, url };
      setQrcodeInfo(qrcodeInfo);
      setQrcodeShow(true);
    } else if (item.id === "copy") {
      // 复制链接
      const input: any = document.getElementById("href");
      input.select();
      document.execCommand("Copy");
      showToast("链接复制成功～");
    }
  };

  useEffect(() => {
    const url = (window.location as any).currentURL;
    setHref(url);
    setShareText(`我在freelog发现一个不错的小说：${exhibit?.exhibitTitle} ${url}`);
  }, [exhibit?.exhibitTitle]);

  useEffect(() => {
    if (!show) setQrcodeShow(false);
  }, [show]);

  return inMobile ? (
    // mobile
    <CSSTransition in={show} classNames="fade" timeout={200} unmountOnExit>
      <div className="mobile-share-wrapper" onClick={() => setShareShow && setShareShow(false)}>
        <div className="exihibit-info" onClick={(e) => e.stopPropagation()}>
          <div className="book-cover-box">
            <img className="book-cover" src={exhibit?.coverImages[0]} alt={exhibit?.exhibitTitle} />
          </div>

          <div className="book-name" title={exhibit?.exhibitTitle}>
            {exhibit?.exhibitTitle}
          </div>
        </div>

        <div className="share-btns" onClick={(e) => e.stopPropagation()}>
          <div className="share-label">快速分享至</div>
          <div className="btns-list">
            {shareBtns.map((item: shareBtnItem, index: number) => {
              return (
                <div className="share-btn-item" key={item.id} onClick={() => share(item)}>
                  <div className="share-btn-icon" style={{ backgroundColor: item.bgColor }}>
                    <i className={`freelog ${item.icon}`}></i>
                  </div>

                  <div className="share-btn-label">{item.name}</div>
                </div>
              );
            })}
          </div>
          <div className="cancel-btn" onClick={() => setShareShow && setShareShow(false)}>
            取消
          </div>
        </div>
      </div>
    </CSSTransition>
  ) : (
    // PC
    <CSSTransition in={show} classNames="fade" timeout={200} unmountOnExit>
      <div className="share-wrapper" onClick={(e) => e.stopPropagation()}>
        <div className="share-popup">
          <div className="share-title">分享</div>

          <input id="href" className="hidden-input" value={href} readOnly />

          <textarea className="textarea" value={shareText} onChange={(e) => setShareText(e.target.value)}></textarea>

          <div className="btns-box">
            <div className="share-btns">
              <div className="share-label">快速分享至：</div>
              {shareBtns.map((item: shareBtnItem, index: number) => {
                return (
                  <div
                    className="share-btn-item"
                    style={{ backgroundColor: item.bgColor }}
                    key={item.id}
                    onClick={() => share(item)}
                  >
                    <i className={`freelog ${item.icon}`}></i>
                  </div>
                );
              })}
            </div>

            <div className="copy-btn" onClick={() => share({ id: "copy", name: "" })}>
              复制链接
            </div>

            <QrcodePopup
              show={qrcodeShow}
              name={qrcodeInfo.name}
              value={qrcodeInfo.url}
              setQrcodeShow={setQrcodeShow}
            />
          </div>
        </div>
      </div>
    </CSSTransition>
  );
};

const QrcodePopup = (props: { show: boolean; name: string; value: string; setQrcodeShow: (show: boolean) => void }) => {
  const { show, name, value, setQrcodeShow } = props;

  return (
    <CSSTransition in={show} classNames="fade" timeout={200} unmountOnExit>
      <div className="qrcode-popup-wrapper" onClick={() => setQrcodeShow(false)}>
        <div className="qrcode-popup" onClick={(e) => e.stopPropagation()}>
          <i className="close-btn freelog fl-icon-guanbi" onClick={() => setQrcodeShow(false)}></i>
          <div className="qrcode-text">分享到{name}</div>
          <QRCode value={value} size={220} />
          <div className="qrcode-text">使用{name}扫一扫完成分享</div>
        </div>
      </div>
    </CSSTransition>
  );
};
